//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace InterpreterLib {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GLangParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHITESPACE=1, COMMA=2, TYPE_DELIMETER=3, TYPE_NAME=4, BOOLEAN=5, INTEGER=6, 
		DECL_VARIABLE=7, IF=8, ELSE=9, WHILE=10, FOR=11, ASSIGNMENT_OPERATOR=12, 
		ADDITIVE_OP=13, MULTIPLICATIVE_OP=14, CARAT=15, LOW_PRIORITY_OP=16, COMPARE_OP=17, 
		LOGICAL_OP=18, BANG=19, IDENTIFIER=20, L_PARENTHESIS=21, R_PARENTHESIS=22, 
		L_BRACE=23, R_BRACE=24, UNKNOWN_CHAR=25;
	public const int
		RULE_statement = 0, RULE_block = 1, RULE_expressionStatement = 2, RULE_forStat = 3, 
		RULE_ifStat = 4, RULE_whileStat = 5, RULE_variableDeclarationStatement = 6, 
		RULE_assignmentExpression = 7, RULE_literal = 8, RULE_unaryExpression = 9, 
		RULE_binaryExpression = 10;
	public static readonly string[] ruleNames = {
		"statement", "block", "expressionStatement", "forStat", "ifStat", "whileStat", 
		"variableDeclarationStatement", "assignmentExpression", "literal", "unaryExpression", 
		"binaryExpression"
	};

	private static readonly string[] _LiteralNames = {
		null, null, "','", "':'", null, null, null, null, "'if'", "'else'", "'while'", 
		"'for'", null, null, null, "'^'", null, null, null, "'!'", null, "'('", 
		"')'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHITESPACE", "COMMA", "TYPE_DELIMETER", "TYPE_NAME", "BOOLEAN", 
		"INTEGER", "DECL_VARIABLE", "IF", "ELSE", "WHILE", "FOR", "ASSIGNMENT_OPERATOR", 
		"ADDITIVE_OP", "MULTIPLICATIVE_OP", "CARAT", "LOW_PRIORITY_OP", "COMPARE_OP", 
		"LOGICAL_OP", "BANG", "IDENTIFIER", "L_PARENTHESIS", "R_PARENTHESIS", 
		"L_BRACE", "R_BRACE", "UNKNOWN_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GLangParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public GLangParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public GLangParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StatementContext : ParserRuleContext {
		public ForStatContext forStat() {
			return GetRuleContext<ForStatContext>(0);
		}
		public WhileStatContext whileStat() {
			return GetRuleContext<WhileStatContext>(0);
		}
		public IfStatContext ifStat() {
			return GetRuleContext<IfStatContext>(0);
		}
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public VariableDeclarationStatementContext variableDeclarationStatement() {
			return GetRuleContext<VariableDeclarationStatementContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public ExpressionStatementContext expressionStatement() {
			return GetRuleContext<ExpressionStatementContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 0, RULE_statement);
		try {
			State = 29;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 22; forStat();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 23; whileStat();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 24; ifStat();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 25; block();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 26; variableDeclarationStatement();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 27; assignmentExpression();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 28; expressionStatement();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public ITerminalNode L_BRACE() { return GetToken(GLangParser.L_BRACE, 0); }
		public ITerminalNode R_BRACE() { return GetToken(GLangParser.R_BRACE, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 31; Match(L_BRACE);
			State = 35;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << BOOLEAN) | (1L << INTEGER) | (1L << DECL_VARIABLE) | (1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << ADDITIVE_OP) | (1L << BANG) | (1L << IDENTIFIER) | (1L << L_PARENTHESIS) | (1L << L_BRACE))) != 0)) {
				{
				{
				State = 32; statement();
				}
				}
				State = 37;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 38; Match(R_BRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionStatementContext : ParserRuleContext {
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ExpressionStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterExpressionStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitExpressionStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionStatementContext expressionStatement() {
		ExpressionStatementContext _localctx = new ExpressionStatementContext(Context, State);
		EnterRule(_localctx, 4, RULE_expressionStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 40; binaryExpression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForStatContext : ParserRuleContext {
		public AssignmentExpressionContext assign;
		public BinaryExpressionContext condition;
		public AssignmentExpressionContext step;
		public StatementContext body;
		public ITerminalNode FOR() { return GetToken(GLangParser.FOR, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(GLangParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(GLangParser.COMMA, i);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public AssignmentExpressionContext[] assignmentExpression() {
			return GetRuleContexts<AssignmentExpressionContext>();
		}
		public AssignmentExpressionContext assignmentExpression(int i) {
			return GetRuleContext<AssignmentExpressionContext>(i);
		}
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public ForStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forStat; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterForStat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitForStat(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitForStat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ForStatContext forStat() {
		ForStatContext _localctx = new ForStatContext(Context, State);
		EnterRule(_localctx, 6, RULE_forStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42; Match(FOR);
			State = 43; Match(L_PARENTHESIS);
			State = 44; _localctx.assign = assignmentExpression();
			State = 45; Match(COMMA);
			State = 46; _localctx.condition = binaryExpression(0);
			State = 47; Match(COMMA);
			State = 48; _localctx.step = assignmentExpression();
			State = 49; Match(R_PARENTHESIS);
			State = 50; _localctx.body = statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatContext : ParserRuleContext {
		public BinaryExpressionContext condition;
		public StatementContext trueBranch;
		public StatementContext falseBranch;
		public ITerminalNode IF() { return GetToken(GLangParser.IF, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ITerminalNode ELSE() { return GetToken(GLangParser.ELSE, 0); }
		public IfStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStat; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterIfStat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitIfStat(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfStat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfStatContext ifStat() {
		IfStatContext _localctx = new IfStatContext(Context, State);
		EnterRule(_localctx, 8, RULE_ifStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52; Match(IF);
			State = 53; Match(L_PARENTHESIS);
			State = 54; _localctx.condition = binaryExpression(0);
			State = 55; Match(R_PARENTHESIS);
			State = 56; _localctx.trueBranch = statement();
			State = 59;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				{
				State = 57; Match(ELSE);
				State = 58; _localctx.falseBranch = statement();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileStatContext : ParserRuleContext {
		public BinaryExpressionContext condition;
		public StatementContext body;
		public ITerminalNode WHILE() { return GetToken(GLangParser.WHILE, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public WhileStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileStat; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterWhileStat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitWhileStat(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhileStat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhileStatContext whileStat() {
		WhileStatContext _localctx = new WhileStatContext(Context, State);
		EnterRule(_localctx, 10, RULE_whileStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61; Match(WHILE);
			State = 62; Match(L_PARENTHESIS);
			State = 63; _localctx.condition = binaryExpression(0);
			State = 64; Match(R_PARENTHESIS);
			State = 65; _localctx.body = statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationStatementContext : ParserRuleContext {
		public ITerminalNode DECL_VARIABLE() { return GetToken(GLangParser.DECL_VARIABLE, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ITerminalNode TYPE_DELIMETER() { return GetToken(GLangParser.TYPE_DELIMETER, 0); }
		public ITerminalNode TYPE_NAME() { return GetToken(GLangParser.TYPE_NAME, 0); }
		public ITerminalNode ASSIGNMENT_OPERATOR() { return GetToken(GLangParser.ASSIGNMENT_OPERATOR, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public VariableDeclarationStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclarationStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterVariableDeclarationStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitVariableDeclarationStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclarationStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationStatementContext variableDeclarationStatement() {
		VariableDeclarationStatementContext _localctx = new VariableDeclarationStatementContext(Context, State);
		EnterRule(_localctx, 12, RULE_variableDeclarationStatement);
		try {
			State = 75;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 67; Match(DECL_VARIABLE);
				State = 68; Match(IDENTIFIER);
				State = 69; Match(TYPE_DELIMETER);
				State = 70; Match(TYPE_NAME);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 71; Match(DECL_VARIABLE);
				State = 72; Match(IDENTIFIER);
				State = 73; Match(ASSIGNMENT_OPERATOR);
				State = 74; binaryExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentExpressionContext : ParserRuleContext {
		public BinaryExpressionContext expr;
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ITerminalNode ASSIGNMENT_OPERATOR() { return GetToken(GLangParser.ASSIGNMENT_OPERATOR, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public AssignmentExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterAssignmentExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitAssignmentExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignmentExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentExpressionContext assignmentExpression() {
		AssignmentExpressionContext _localctx = new AssignmentExpressionContext(Context, State);
		EnterRule(_localctx, 14, RULE_assignmentExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77; Match(IDENTIFIER);
			State = 78; Match(ASSIGNMENT_OPERATOR);
			State = 79; _localctx.expr = binaryExpression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public ITerminalNode INTEGER() { return GetToken(GLangParser.INTEGER, 0); }
		public ITerminalNode BOOLEAN() { return GetToken(GLangParser.BOOLEAN, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 16, RULE_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << BOOLEAN) | (1L << INTEGER) | (1L << IDENTIFIER))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryExpressionContext : ParserRuleContext {
		public IToken op;
		public LiteralContext atom;
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public UnaryExpressionContext unaryExpression() {
			return GetRuleContext<UnaryExpressionContext>(0);
		}
		public ITerminalNode ADDITIVE_OP() { return GetToken(GLangParser.ADDITIVE_OP, 0); }
		public ITerminalNode BANG() { return GetToken(GLangParser.BANG, 0); }
		public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public UnaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterUnaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitUnaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryExpressionContext unaryExpression() {
		UnaryExpressionContext _localctx = new UnaryExpressionContext(Context, State);
		EnterRule(_localctx, 18, RULE_unaryExpression);
		int _la;
		try {
			State = 90;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case L_PARENTHESIS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 83; Match(L_PARENTHESIS);
				State = 84; binaryExpression(0);
				State = 85; Match(R_PARENTHESIS);
				}
				break;
			case ADDITIVE_OP:
			case BANG:
				EnterOuterAlt(_localctx, 2);
				{
				State = 87;
				_localctx.op = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==ADDITIVE_OP || _la==BANG) ) {
					_localctx.op = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 88; unaryExpression();
				}
				break;
			case BOOLEAN:
			case INTEGER:
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 3);
				{
				State = 89; _localctx.atom = literal();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinaryExpressionContext : ParserRuleContext {
		public BinaryExpressionContext left;
		public UnaryExpressionContext atom;
		public IToken op;
		public BinaryExpressionContext right;
		public UnaryExpressionContext unaryExpression() {
			return GetRuleContext<UnaryExpressionContext>(0);
		}
		public BinaryExpressionContext[] binaryExpression() {
			return GetRuleContexts<BinaryExpressionContext>();
		}
		public BinaryExpressionContext binaryExpression(int i) {
			return GetRuleContext<BinaryExpressionContext>(i);
		}
		public ITerminalNode CARAT() { return GetToken(GLangParser.CARAT, 0); }
		public ITerminalNode MULTIPLICATIVE_OP() { return GetToken(GLangParser.MULTIPLICATIVE_OP, 0); }
		public ITerminalNode ADDITIVE_OP() { return GetToken(GLangParser.ADDITIVE_OP, 0); }
		public ITerminalNode LOW_PRIORITY_OP() { return GetToken(GLangParser.LOW_PRIORITY_OP, 0); }
		public ITerminalNode COMPARE_OP() { return GetToken(GLangParser.COMPARE_OP, 0); }
		public ITerminalNode LOGICAL_OP() { return GetToken(GLangParser.LOGICAL_OP, 0); }
		public BinaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBinaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBinaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BinaryExpressionContext binaryExpression() {
		return binaryExpression(0);
	}

	private BinaryExpressionContext binaryExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BinaryExpressionContext _localctx = new BinaryExpressionContext(Context, _parentState);
		BinaryExpressionContext _prevctx = _localctx;
		int _startState = 20;
		EnterRecursionRule(_localctx, 20, RULE_binaryExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 93; _localctx.atom = unaryExpression();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 115;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 113;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
					case 1:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 95;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 96; _localctx.op = Match(CARAT);
						State = 97; _localctx.right = binaryExpression(8);
						}
						break;
					case 2:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 98;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 99; _localctx.op = Match(MULTIPLICATIVE_OP);
						State = 100; _localctx.right = binaryExpression(7);
						}
						break;
					case 3:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 101;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 102; _localctx.op = Match(ADDITIVE_OP);
						State = 103; _localctx.right = binaryExpression(6);
						}
						break;
					case 4:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 104;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 105; _localctx.op = Match(LOW_PRIORITY_OP);
						State = 106; _localctx.right = binaryExpression(5);
						}
						break;
					case 5:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 107;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 108; _localctx.op = Match(COMPARE_OP);
						State = 109; _localctx.right = binaryExpression(4);
						}
						break;
					case 6:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 110;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 111; _localctx.op = Match(LOGICAL_OP);
						State = 112; _localctx.right = binaryExpression(3);
						}
						break;
					}
					} 
				}
				State = 117;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 10: return binaryExpression_sempred((BinaryExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool binaryExpression_sempred(BinaryExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 7);
		case 1: return Precpred(Context, 6);
		case 2: return Precpred(Context, 5);
		case 3: return Precpred(Context, 4);
		case 4: return Precpred(Context, 3);
		case 5: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x1B', 'y', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', ' ', '\n', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '$', '\n', '\x3', '\f', 
		'\x3', '\xE', '\x3', '\'', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '>', '\n', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', 'N', '\n', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x5', '\v', ']', '\n', '\v', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', 't', '\n', '\f', '\f', 
		'\f', '\xE', '\f', 'w', '\v', '\f', '\x3', '\f', '\x2', '\x3', '\x16', 
		'\r', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', 
		'\x16', '\x2', '\x4', '\x4', '\x2', '\a', '\b', '\x16', '\x16', '\x4', 
		'\x2', '\xF', '\xF', '\x15', '\x15', '\x2', '~', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x4', '!', '\x3', '\x2', '\x2', '\x2', '\x6', '*', 
		'\x3', '\x2', '\x2', '\x2', '\b', ',', '\x3', '\x2', '\x2', '\x2', '\n', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\f', '?', '\x3', '\x2', '\x2', '\x2', 
		'\xE', 'M', '\x3', '\x2', '\x2', '\x2', '\x10', 'O', '\x3', '\x2', '\x2', 
		'\x2', '\x12', 'S', '\x3', '\x2', '\x2', '\x2', '\x14', '\\', '\x3', '\x2', 
		'\x2', '\x2', '\x16', '^', '\x3', '\x2', '\x2', '\x2', '\x18', ' ', '\x5', 
		'\b', '\x5', '\x2', '\x19', ' ', '\x5', '\f', '\a', '\x2', '\x1A', ' ', 
		'\x5', '\n', '\x6', '\x2', '\x1B', ' ', '\x5', '\x4', '\x3', '\x2', '\x1C', 
		' ', '\x5', '\xE', '\b', '\x2', '\x1D', ' ', '\x5', '\x10', '\t', '\x2', 
		'\x1E', ' ', '\x5', '\x6', '\x4', '\x2', '\x1F', '\x18', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\x19', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\x1F', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\x1E', '\x3', '\x2', '\x2', '\x2', ' ', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '!', '%', '\a', '\x19', '\x2', '\x2', '\"', 
		'$', '\x5', '\x2', '\x2', '\x2', '#', '\"', '\x3', '\x2', '\x2', '\x2', 
		'$', '\'', '\x3', '\x2', '\x2', '\x2', '%', '#', '\x3', '\x2', '\x2', 
		'\x2', '%', '&', '\x3', '\x2', '\x2', '\x2', '&', '(', '\x3', '\x2', '\x2', 
		'\x2', '\'', '%', '\x3', '\x2', '\x2', '\x2', '(', ')', '\a', '\x1A', 
		'\x2', '\x2', ')', '\x5', '\x3', '\x2', '\x2', '\x2', '*', '+', '\x5', 
		'\x16', '\f', '\x2', '+', '\a', '\x3', '\x2', '\x2', '\x2', ',', '-', 
		'\a', '\r', '\x2', '\x2', '-', '.', '\a', '\x17', '\x2', '\x2', '.', '/', 
		'\x5', '\x10', '\t', '\x2', '/', '\x30', '\a', '\x4', '\x2', '\x2', '\x30', 
		'\x31', '\x5', '\x16', '\f', '\x2', '\x31', '\x32', '\a', '\x4', '\x2', 
		'\x2', '\x32', '\x33', '\x5', '\x10', '\t', '\x2', '\x33', '\x34', '\a', 
		'\x18', '\x2', '\x2', '\x34', '\x35', '\x5', '\x2', '\x2', '\x2', '\x35', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\a', '\n', '\x2', '\x2', 
		'\x37', '\x38', '\a', '\x17', '\x2', '\x2', '\x38', '\x39', '\x5', '\x16', 
		'\f', '\x2', '\x39', ':', '\a', '\x18', '\x2', '\x2', ':', '=', '\x5', 
		'\x2', '\x2', '\x2', ';', '<', '\a', '\v', '\x2', '\x2', '<', '>', '\x5', 
		'\x2', '\x2', '\x2', '=', ';', '\x3', '\x2', '\x2', '\x2', '=', '>', '\x3', 
		'\x2', '\x2', '\x2', '>', '\v', '\x3', '\x2', '\x2', '\x2', '?', '@', 
		'\a', '\f', '\x2', '\x2', '@', '\x41', '\a', '\x17', '\x2', '\x2', '\x41', 
		'\x42', '\x5', '\x16', '\f', '\x2', '\x42', '\x43', '\a', '\x18', '\x2', 
		'\x2', '\x43', '\x44', '\x5', '\x2', '\x2', '\x2', '\x44', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\t', '\x2', '\x2', '\x46', 
		'G', '\a', '\x16', '\x2', '\x2', 'G', 'H', '\a', '\x5', '\x2', '\x2', 
		'H', 'N', '\a', '\x6', '\x2', '\x2', 'I', 'J', '\a', '\t', '\x2', '\x2', 
		'J', 'K', '\a', '\x16', '\x2', '\x2', 'K', 'L', '\a', '\xE', '\x2', '\x2', 
		'L', 'N', '\x5', '\x16', '\f', '\x2', 'M', '\x45', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'I', '\x3', '\x2', '\x2', '\x2', 'N', '\xF', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\a', '\x16', '\x2', '\x2', 'P', 'Q', '\a', '\xE', 
		'\x2', '\x2', 'Q', 'R', '\x5', '\x16', '\f', '\x2', 'R', '\x11', '\x3', 
		'\x2', '\x2', '\x2', 'S', 'T', '\t', '\x2', '\x2', '\x2', 'T', '\x13', 
		'\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '\x17', '\x2', '\x2', 'V', 
		'W', '\x5', '\x16', '\f', '\x2', 'W', 'X', '\a', '\x18', '\x2', '\x2', 
		'X', ']', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\t', '\x3', '\x2', '\x2', 
		'Z', ']', '\x5', '\x14', '\v', '\x2', '[', ']', '\x5', '\x12', '\n', '\x2', 
		'\\', 'U', '\x3', '\x2', '\x2', '\x2', '\\', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '\\', '[', '\x3', '\x2', '\x2', '\x2', ']', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '^', '_', '\b', '\f', '\x1', '\x2', '_', '`', '\x5', '\x14', 
		'\v', '\x2', '`', 'u', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\f', 
		'\t', '\x2', '\x2', '\x62', '\x63', '\a', '\x11', '\x2', '\x2', '\x63', 
		't', '\x5', '\x16', '\f', '\n', '\x64', '\x65', '\f', '\b', '\x2', '\x2', 
		'\x65', '\x66', '\a', '\x10', '\x2', '\x2', '\x66', 't', '\x5', '\x16', 
		'\f', '\t', 'g', 'h', '\f', '\a', '\x2', '\x2', 'h', 'i', '\a', '\xF', 
		'\x2', '\x2', 'i', 't', '\x5', '\x16', '\f', '\b', 'j', 'k', '\f', '\x6', 
		'\x2', '\x2', 'k', 'l', '\a', '\x12', '\x2', '\x2', 'l', 't', '\x5', '\x16', 
		'\f', '\a', 'm', 'n', '\f', '\x5', '\x2', '\x2', 'n', 'o', '\a', '\x13', 
		'\x2', '\x2', 'o', 't', '\x5', '\x16', '\f', '\x6', 'p', 'q', '\f', '\x4', 
		'\x2', '\x2', 'q', 'r', '\a', '\x14', '\x2', '\x2', 'r', 't', '\x5', '\x16', 
		'\f', '\x5', 's', '\x61', '\x3', '\x2', '\x2', '\x2', 's', '\x64', '\x3', 
		'\x2', '\x2', '\x2', 's', 'g', '\x3', '\x2', '\x2', '\x2', 's', 'j', '\x3', 
		'\x2', '\x2', '\x2', 's', 'm', '\x3', '\x2', '\x2', '\x2', 's', 'p', '\x3', 
		'\x2', '\x2', '\x2', 't', 'w', '\x3', '\x2', '\x2', '\x2', 'u', 's', '\x3', 
		'\x2', '\x2', '\x2', 'u', 'v', '\x3', '\x2', '\x2', '\x2', 'v', '\x17', 
		'\x3', '\x2', '\x2', '\x2', 'w', 'u', '\x3', '\x2', '\x2', '\x2', '\t', 
		'\x1F', '%', '=', 'M', '\\', 's', 'u',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace InterpreterLib
