//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace InterpreterLib {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GLangLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHITESPACE=1, INTEGER=2, BOOLEAN=3, DECL_VARIABLE=4, IF=5, ELSE=6, ADDITIVE_OP=7, 
		MULTIPLICATIVE_OP=8, LOW_PRIORITY_OP=9, CARAT=10, ASSIGNMENT_OPERATOR=11, 
		BANG=12, IDENTIFIER=13, L_BRACKET=14, R_BRACKET=15, L_BRACE=16, R_BRACE=17, 
		UNKNOWN_CHAR=18;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"DIGITS", "TRUE", "FALSE", "CHARACTER", "VAR", "VAL", "EQUALITY_OPERATOR", 
		"LOGICAL_OPERATOR", "MOD_OPERATOR", "WHITESPACE", "INTEGER", "BOOLEAN", 
		"DECL_VARIABLE", "IF", "ELSE", "ADDITIVE_OP", "MULTIPLICATIVE_OP", "LOW_PRIORITY_OP", 
		"CARAT", "ASSIGNMENT_OPERATOR", "BANG", "IDENTIFIER", "L_BRACKET", "R_BRACKET", 
		"L_BRACE", "R_BRACE", "UNKNOWN_CHAR"
	};


	public GLangLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GLangLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, "'if'", "'else'", null, null, null, "'^'", 
		"'='", "'!'", null, "'('", "')'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHITESPACE", "INTEGER", "BOOLEAN", "DECL_VARIABLE", "IF", "ELSE", 
		"ADDITIVE_OP", "MULTIPLICATIVE_OP", "LOW_PRIORITY_OP", "CARAT", "ASSIGNMENT_OPERATOR", 
		"BANG", "IDENTIFIER", "L_BRACKET", "R_BRACKET", "L_BRACE", "R_BRACE", 
		"UNKNOWN_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GLangLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x14', '\x9A', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x3', '\x2', '\x6', 
		'\x2', ';', '\n', '\x2', '\r', '\x2', '\xE', '\x2', '<', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x5', '\t', '[', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\v', '\x6', '\v', '\x62', '\n', '\v', '\r', 
		'\v', '\xE', '\v', '\x63', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x5', '\r', 'l', '\n', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x5', '\xE', 'p', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\x81', '\n', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\a', 
		'\x17', '\x8C', '\n', '\x17', '\f', '\x17', '\xE', '\x17', '\x8F', '\v', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x5', '\x2', '\a', '\x2', 
		'\t', '\x2', '\v', '\x2', '\r', '\x2', '\xF', '\x2', '\x11', '\x2', '\x13', 
		'\x2', '\x15', '\x3', '\x17', '\x4', '\x19', '\x5', '\x1B', '\x6', '\x1D', 
		'\a', '\x1F', '\b', '!', '\t', '#', '\n', '%', '\v', '\'', '\f', ')', 
		'\r', '+', '\xE', '-', '\xF', '/', '\x10', '\x31', '\x11', '\x33', '\x12', 
		'\x35', '\x13', '\x37', '\x14', '\x3', '\x2', '\b', '\x4', '\x2', 'V', 
		'V', 'v', 'v', '\x4', '\x2', 'H', 'H', 'h', 'h', '\x4', '\x2', '\x43', 
		'\\', '\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x4', '\x2', '-', '-', '/', '/', '\x4', '\x2', ',', ',', '\x31', '\x31', 
		'\x2', '\x99', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x3', ':', '\x3', '\x2', '\x2', '\x2', 
		'\x5', '>', '\x3', '\x2', '\x2', '\x2', '\a', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\t', 'I', '\x3', '\x2', '\x2', '\x2', '\v', 'K', '\x3', '\x2', 
		'\x2', '\x2', '\r', 'O', '\x3', '\x2', '\x2', '\x2', '\xF', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x11', 'Z', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\\', '\x3', '\x2', '\x2', '\x2', '\x15', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x17', 'g', '\x3', '\x2', '\x2', '\x2', '\x19', 'k', '\x3', '\x2', 
		'\x2', '\x2', '\x1B', 'o', '\x3', '\x2', '\x2', '\x2', '\x1D', 'q', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', 't', '\x3', '\x2', '\x2', '\x2', '!', 'y', 
		'\x3', '\x2', '\x2', '\x2', '#', '{', '\x3', '\x2', '\x2', '\x2', '%', 
		'\x80', '\x3', '\x2', '\x2', '\x2', '\'', '\x82', '\x3', '\x2', '\x2', 
		'\x2', ')', '\x84', '\x3', '\x2', '\x2', '\x2', '+', '\x86', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x88', '\x3', '\x2', '\x2', '\x2', '/', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x92', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\x94', '\x3', '\x2', '\x2', '\x2', '\x35', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '\x37', '\x98', '\x3', '\x2', '\x2', '\x2', '\x39', ';', '\x4', 
		'\x32', ';', '\x2', ':', '\x39', '\x3', '\x2', '\x2', '\x2', ';', '<', 
		'\x3', '\x2', '\x2', '\x2', '<', ':', '\x3', '\x2', '\x2', '\x2', '<', 
		'=', '\x3', '\x2', '\x2', '\x2', '=', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'>', '?', '\t', '\x2', '\x2', '\x2', '?', '@', '\a', 't', '\x2', '\x2', 
		'@', '\x41', '\a', 'w', '\x2', '\x2', '\x41', '\x42', '\a', 'g', '\x2', 
		'\x2', '\x42', '\x6', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\t', 
		'\x3', '\x2', '\x2', '\x44', '\x45', '\a', '\x63', '\x2', '\x2', '\x45', 
		'\x46', '\a', 'n', '\x2', '\x2', '\x46', 'G', '\a', 'u', '\x2', '\x2', 
		'G', 'H', '\a', 'g', '\x2', '\x2', 'H', '\b', '\x3', '\x2', '\x2', '\x2', 
		'I', 'J', '\t', '\x4', '\x2', '\x2', 'J', '\n', '\x3', '\x2', '\x2', '\x2', 
		'K', 'L', '\a', 'x', '\x2', '\x2', 'L', 'M', '\a', '\x63', '\x2', '\x2', 
		'M', 'N', '\a', 't', '\x2', '\x2', 'N', '\f', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\a', 'x', '\x2', '\x2', 'P', 'Q', '\a', '\x63', '\x2', '\x2', 
		'Q', 'R', '\a', 'n', '\x2', '\x2', 'R', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\a', '?', '\x2', '\x2', 'T', 'U', '\a', '?', '\x2', '\x2', 
		'U', '\x10', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\a', '(', '\x2', '\x2', 
		'W', '[', '\a', '(', '\x2', '\x2', 'X', 'Y', '\a', '~', '\x2', '\x2', 
		'Y', '[', '\a', '~', '\x2', '\x2', 'Z', 'V', '\x3', '\x2', '\x2', '\x2', 
		'Z', 'X', '\x3', '\x2', '\x2', '\x2', '[', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\a', 'o', '\x2', '\x2', ']', '^', '\a', 'q', '\x2', 
		'\x2', '^', '_', '\a', '\x66', '\x2', '\x2', '_', '\x14', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x62', '\t', '\x5', '\x2', '\x2', '\x61', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '\x63', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x65', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\b', 
		'\v', '\x2', '\x2', '\x66', '\x16', '\x3', '\x2', '\x2', '\x2', 'g', 'h', 
		'\x5', '\x3', '\x2', '\x2', 'h', '\x18', '\x3', '\x2', '\x2', '\x2', 'i', 
		'l', '\x5', '\x5', '\x3', '\x2', 'j', 'l', '\x5', '\a', '\x4', '\x2', 
		'k', 'i', '\x3', '\x2', '\x2', '\x2', 'k', 'j', '\x3', '\x2', '\x2', '\x2', 
		'l', '\x1A', '\x3', '\x2', '\x2', '\x2', 'm', 'p', '\x5', '\r', '\a', 
		'\x2', 'n', 'p', '\x5', '\v', '\x6', '\x2', 'o', 'm', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'n', '\x3', '\x2', '\x2', '\x2', 'p', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', 'q', 'r', '\a', 'k', '\x2', '\x2', 'r', 's', '\a', 'h', 
		'\x2', '\x2', 's', '\x1E', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', 
		'g', '\x2', '\x2', 'u', 'v', '\a', 'n', '\x2', '\x2', 'v', 'w', '\a', 
		'u', '\x2', '\x2', 'w', 'x', '\a', 'g', '\x2', '\x2', 'x', ' ', '\x3', 
		'\x2', '\x2', '\x2', 'y', 'z', '\t', '\x6', '\x2', '\x2', 'z', '\"', '\x3', 
		'\x2', '\x2', '\x2', '{', '|', '\t', '\a', '\x2', '\x2', '|', '$', '\x3', 
		'\x2', '\x2', '\x2', '}', '\x81', '\x5', '\x13', '\n', '\x2', '~', '\x81', 
		'\x5', '\xF', '\b', '\x2', '\x7F', '\x81', '\x5', '\x11', '\t', '\x2', 
		'\x80', '}', '\x3', '\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', '&', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x83', '\a', '`', '\x2', '\x2', '\x83', 
		'(', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '?', '\x2', '\x2', 
		'\x85', '*', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', '#', '\x2', 
		'\x2', '\x87', ',', '\x3', '\x2', '\x2', '\x2', '\x88', '\x8D', '\x5', 
		'\t', '\x5', '\x2', '\x89', '\x8C', '\x5', '\t', '\x5', '\x2', '\x8A', 
		'\x8C', '\a', '\x61', '\x2', '\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '.', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\a', 
		'*', '\x2', '\x2', '\x91', '\x30', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x93', '\a', '+', '\x2', '\x2', '\x93', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x95', '\a', '}', '\x2', '\x2', '\x95', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x96', '\x97', '\a', '\x7F', '\x2', '\x2', '\x97', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\v', '\x2', '\x2', 
		'\x2', '\x99', '\x38', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', '<', 'Z', 
		'\x63', 'k', 'o', '\x80', '\x8B', '\x8D', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace InterpreterLib
