//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace InterpreterLib {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IGLangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] GLangParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] GLangParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] GLangParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] GLangParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] GLangParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] GLangParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLangParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] GLangParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLangParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] GLangParser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLangParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] GLangParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLangParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] GLangParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLangParser.binaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryExpression([NotNull] GLangParser.BinaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLangParser.binaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryExpression([NotNull] GLangParser.BinaryExpressionContext context);
}
} // namespace InterpreterLib
