//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace InterpreterLib {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GLangLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHITESPACE=1, COMMA=2, TYPE_DELIMETER=3, TYPE_NAME=4, BOOLEAN=5, INTEGER=6, 
		DECL_VARIABLE=7, IF=8, ELSE=9, WHILE=10, FOR=11, ASSIGNMENT_OPERATOR=12, 
		ADDITIVE_OP=13, MULTIPLICATIVE_OP=14, CARAT=15, LOW_PRIORITY_OP=16, COMPARE_OP=17, 
		LOGICAL_OP=18, BANG=19, IDENTIFIER=20, L_PARENTHESIS=21, R_PARENTHESIS=22, 
		L_BRACE=23, R_BRACE=24, UNKNOWN_CHAR=25;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"DIGITS", "TRUE", "FALSE", "CHARACTER", "VAR", "VAL", "INT", "BOOL", "EQUALITY_OPERATOR", 
		"GREATER", "LESSER", "GREATER_STRICT", "LESSER_STRICT", "MOD_OPERATOR", 
		"WHITESPACE", "COMMA", "TYPE_DELIMETER", "TYPE_NAME", "BOOLEAN", "INTEGER", 
		"DECL_VARIABLE", "IF", "ELSE", "WHILE", "FOR", "ASSIGNMENT_OPERATOR", 
		"ADDITIVE_OP", "MULTIPLICATIVE_OP", "CARAT", "LOW_PRIORITY_OP", "COMPARE_OP", 
		"LOGICAL_OP", "BANG", "IDENTIFIER", "L_PARENTHESIS", "R_PARENTHESIS", 
		"L_BRACE", "R_BRACE", "UNKNOWN_CHAR"
	};


	public GLangLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GLangLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, "','", "':'", null, null, null, null, "'if'", "'else'", "'while'", 
		"'for'", null, null, null, "'^'", null, null, null, "'!'", null, "'('", 
		"')'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHITESPACE", "COMMA", "TYPE_DELIMETER", "TYPE_NAME", "BOOLEAN", 
		"INTEGER", "DECL_VARIABLE", "IF", "ELSE", "WHILE", "FOR", "ASSIGNMENT_OPERATOR", 
		"ADDITIVE_OP", "MULTIPLICATIVE_OP", "CARAT", "LOW_PRIORITY_OP", "COMPARE_OP", 
		"LOGICAL_OP", "BANG", "IDENTIFIER", "L_PARENTHESIS", "R_PARENTHESIS", 
		"L_BRACE", "R_BRACE", "UNKNOWN_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GLangLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1B', '\xE4', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x3', '\x2', 
		'\x6', '\x2', 'S', '\n', '\x2', '\r', '\x2', '\xE', '\x2', 'T', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x6', '\x10', '\x87', '\n', '\x10', '\r', '\x10', '\xE', '\x10', '\x88', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\x93', '\n', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', '\x97', '\n', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x5', '\x16', 
		'\x9D', '\n', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x5', '\x1B', '\xBA', 
		'\n', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', 
		'\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x5', ' ', '\xC9', '\n', 
		' ', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x5', '!', '\xCF', 
		'\n', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', '#', 
		'\a', '#', '\xD6', '\n', '#', '\f', '#', '\xE', '#', '\xD9', '\v', '#', 
		'\x3', '$', '\x3', '$', '\x3', '%', '\x3', '%', '\x3', '&', '\x3', '&', 
		'\x3', '\'', '\x3', '\'', '\x3', '(', '\x3', '(', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x5', '\x2', '\a', '\x2', '\t', '\x2', '\v', '\x2', '\r', '\x2', 
		'\xF', '\x2', '\x11', '\x2', '\x13', '\x2', '\x15', '\x2', '\x17', '\x2', 
		'\x19', '\x2', '\x1B', '\x2', '\x1D', '\x2', '\x1F', '\x3', '!', '\x4', 
		'#', '\x5', '%', '\x6', '\'', '\a', ')', '\b', '+', '\t', '-', '\n', '/', 
		'\v', '\x31', '\f', '\x33', '\r', '\x35', '\xE', '\x37', '\xF', '\x39', 
		'\x10', ';', '\x11', '=', '\x12', '?', '\x13', '\x41', '\x14', '\x43', 
		'\x15', '\x45', '\x16', 'G', '\x17', 'I', '\x18', 'K', '\x19', 'M', '\x1A', 
		'O', '\x1B', '\x3', '\x2', '\b', '\x4', '\x2', 'V', 'V', 'v', 'v', '\x4', 
		'\x2', 'H', 'H', 'h', 'h', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x5', 
		'\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', '\x2', '-', '-', '/', 
		'/', '\x4', '\x2', ',', ',', '\x31', '\x31', '\x2', '\xE5', '\x2', '\x1F', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x43', '\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x2', 'M', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'O', '\x3', '\x2', '\x2', '\x2', '\x3', 'R', 
		'\x3', '\x2', '\x2', '\x2', '\x5', 'V', '\x3', '\x2', '\x2', '\x2', '\a', 
		'[', '\x3', '\x2', '\x2', '\x2', '\t', '\x61', '\x3', '\x2', '\x2', '\x2', 
		'\v', '\x63', '\x3', '\x2', '\x2', '\x2', '\r', 'g', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'k', '\x3', '\x2', '\x2', '\x2', '\x11', 'o', '\x3', '\x2', 
		'\x2', '\x2', '\x13', 't', '\x3', '\x2', '\x2', '\x2', '\x15', 'w', '\x3', 
		'\x2', '\x2', '\x2', '\x17', 'z', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'}', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x81', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '!', '\x8C', '\x3', '\x2', '\x2', '\x2', '#', '\x8E', 
		'\x3', '\x2', '\x2', '\x2', '%', '\x92', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\x96', '\x3', '\x2', '\x2', '\x2', ')', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '+', '\x9C', '\x3', '\x2', '\x2', '\x2', '-', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '/', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x31', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\xAC', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\xB9', '\x3', '\x2', '\x2', '\x2', '\x37', '\xBB', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\xBD', '\x3', '\x2', '\x2', '\x2', ';', '\xBF', 
		'\x3', '\x2', '\x2', '\x2', '=', '\xC1', '\x3', '\x2', '\x2', '\x2', '?', 
		'\xC8', '\x3', '\x2', '\x2', '\x2', '\x41', '\xCE', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\xD0', '\x3', '\x2', '\x2', '\x2', '\x45', '\xD2', '\x3', 
		'\x2', '\x2', '\x2', 'G', '\xDA', '\x3', '\x2', '\x2', '\x2', 'I', '\xDC', 
		'\x3', '\x2', '\x2', '\x2', 'K', '\xDE', '\x3', '\x2', '\x2', '\x2', 'M', 
		'\xE0', '\x3', '\x2', '\x2', '\x2', 'O', '\xE2', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'S', '\x4', '\x32', ';', '\x2', 'R', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'U', '\x3', '\x2', '\x2', '\x2', 'U', '\x4', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'W', '\t', '\x2', '\x2', '\x2', 'W', 'X', '\a', 't', 
		'\x2', '\x2', 'X', 'Y', '\a', 'w', '\x2', '\x2', 'Y', 'Z', '\a', 'g', 
		'\x2', '\x2', 'Z', '\x6', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\t', 
		'\x3', '\x2', '\x2', '\\', ']', '\a', '\x63', '\x2', '\x2', ']', '^', 
		'\a', 'n', '\x2', '\x2', '^', '_', '\a', 'u', '\x2', '\x2', '_', '`', 
		'\a', 'g', '\x2', '\x2', '`', '\b', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'\x62', '\t', '\x4', '\x2', '\x2', '\x62', '\n', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\a', 'x', '\x2', '\x2', '\x64', '\x65', '\a', 
		'\x63', '\x2', '\x2', '\x65', '\x66', '\a', 't', '\x2', '\x2', '\x66', 
		'\f', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', 'x', '\x2', '\x2', 'h', 
		'i', '\a', '\x63', '\x2', '\x2', 'i', 'j', '\a', 'n', '\x2', '\x2', 'j', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', 'k', '\x2', '\x2', 
		'l', 'm', '\a', 'p', '\x2', '\x2', 'm', 'n', '\a', 'v', '\x2', '\x2', 
		'n', '\x10', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\a', '\x64', '\x2', 
		'\x2', 'p', 'q', '\a', 'q', '\x2', '\x2', 'q', 'r', '\a', 'q', '\x2', 
		'\x2', 'r', 's', '\a', 'n', '\x2', '\x2', 's', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 't', 'u', '\a', '?', '\x2', '\x2', 'u', 'v', '\a', '?', '\x2', 
		'\x2', 'v', '\x14', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', '@', '\x2', 
		'\x2', 'x', 'y', '\a', '?', '\x2', '\x2', 'y', '\x16', '\x3', '\x2', '\x2', 
		'\x2', 'z', '{', '\a', '>', '\x2', '\x2', '{', '|', '\a', '?', '\x2', 
		'\x2', '|', '\x18', '\x3', '\x2', '\x2', '\x2', '}', '~', '\a', '@', '\x2', 
		'\x2', '~', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\a', 
		'>', '\x2', '\x2', '\x80', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\a', 'o', '\x2', '\x2', '\x82', '\x83', '\a', 'q', '\x2', '\x2', 
		'\x83', '\x84', '\a', '\x66', '\x2', '\x2', '\x84', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\x85', '\x87', '\t', '\x5', '\x2', '\x2', '\x86', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\x3', '\x2', '\x2', '\x2', 
		'\x88', '\x86', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\x3', '\x2', 
		'\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', 
		'\b', '\x10', '\x2', '\x2', '\x8B', ' ', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8D', '\a', '.', '\x2', '\x2', '\x8D', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x8E', '\x8F', '\a', '<', '\x2', '\x2', '\x8F', '$', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x93', '\x5', '\xF', '\b', '\x2', '\x91', '\x93', '\x5', 
		'\x11', '\t', '\x2', '\x92', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '&', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x97', '\x5', '\x5', '\x3', '\x2', '\x95', '\x97', '\x5', 
		'\a', '\x4', '\x2', '\x96', '\x94', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '(', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x99', '\x5', '\x3', '\x2', '\x2', '\x99', '*', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x9D', '\x5', '\r', '\a', '\x2', '\x9B', 
		'\x9D', '\x5', '\v', '\x6', '\x2', '\x9C', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9D', ',', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x9F', '\a', 'k', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', 'h', '\x2', '\x2', '\xA0', '.', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\xA2', '\a', 'g', '\x2', '\x2', '\xA2', '\xA3', '\a', 'n', '\x2', 
		'\x2', '\xA3', '\xA4', '\a', 'u', '\x2', '\x2', '\xA4', '\xA5', '\a', 
		'g', '\x2', '\x2', '\xA5', '\x30', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', 'y', '\x2', '\x2', '\xA7', '\xA8', '\a', 'j', '\x2', '\x2', 
		'\xA8', '\xA9', '\a', 'k', '\x2', '\x2', '\xA9', '\xAA', '\a', 'n', '\x2', 
		'\x2', '\xAA', '\xAB', '\a', 'g', '\x2', '\x2', '\xAB', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAD', '\a', 'h', '\x2', '\x2', '\xAD', 
		'\xAE', '\a', 'q', '\x2', '\x2', '\xAE', '\xAF', '\a', 't', '\x2', '\x2', 
		'\xAF', '\x34', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\a', '-', 
		'\x2', '\x2', '\xB1', '\xBA', '\a', '?', '\x2', '\x2', '\xB2', '\xB3', 
		'\a', '/', '\x2', '\x2', '\xB3', '\xBA', '\a', '?', '\x2', '\x2', '\xB4', 
		'\xB5', '\a', ',', '\x2', '\x2', '\xB5', '\xBA', '\a', '?', '\x2', '\x2', 
		'\xB6', '\xB7', '\a', '\x31', '\x2', '\x2', '\xB7', '\xBA', '\a', '?', 
		'\x2', '\x2', '\xB8', '\xBA', '\a', '?', '\x2', '\x2', '\xB9', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', '\xB9', '\xB2', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB6', '\x3', '\x2', 
		'\x2', '\x2', '\xB9', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xBA', '\x36', 
		'\x3', '\x2', '\x2', '\x2', '\xBB', '\xBC', '\t', '\x6', '\x2', '\x2', 
		'\xBC', '\x38', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBE', '\t', '\a', 
		'\x2', '\x2', '\xBE', ':', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', 
		'\a', '`', '\x2', '\x2', '\xC0', '<', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC2', '\x5', '\x1D', '\xF', '\x2', '\xC2', '>', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xC9', '\x5', '\x13', '\n', '\x2', '\xC4', '\xC9', '\x5', 
		'\x15', '\v', '\x2', '\xC5', '\xC9', '\x5', '\x17', '\f', '\x2', '\xC6', 
		'\xC9', '\x5', '\x19', '\r', '\x2', '\xC7', '\xC9', '\x5', '\x1B', '\xE', 
		'\x2', '\xC8', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC8', 
		'\xC6', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '@', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\a', 
		'(', '\x2', '\x2', '\xCB', '\xCF', '\a', '(', '\x2', '\x2', '\xCC', '\xCD', 
		'\a', '~', '\x2', '\x2', '\xCD', '\xCF', '\a', '~', '\x2', '\x2', '\xCE', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\x42', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', '\a', 
		'#', '\x2', '\x2', '\xD1', '\x44', '\x3', '\x2', '\x2', '\x2', '\xD2', 
		'\xD7', '\x5', '\t', '\x5', '\x2', '\xD3', '\xD6', '\x5', '\t', '\x5', 
		'\x2', '\xD4', '\xD6', '\a', '\x61', '\x2', '\x2', '\xD5', '\xD3', '\x3', 
		'\x2', '\x2', '\x2', '\xD5', '\xD4', '\x3', '\x2', '\x2', '\x2', '\xD6', 
		'\xD9', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\xD7', '\xD8', '\x3', '\x2', '\x2', '\x2', '\xD8', '\x46', '\x3', 
		'\x2', '\x2', '\x2', '\xD9', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xDA', 
		'\xDB', '\a', '*', '\x2', '\x2', '\xDB', 'H', '\x3', '\x2', '\x2', '\x2', 
		'\xDC', '\xDD', '\a', '+', '\x2', '\x2', '\xDD', 'J', '\x3', '\x2', '\x2', 
		'\x2', '\xDE', '\xDF', '\a', '}', '\x2', '\x2', '\xDF', 'L', '\x3', '\x2', 
		'\x2', '\x2', '\xE0', '\xE1', '\a', '\x7F', '\x2', '\x2', '\xE1', 'N', 
		'\x3', '\x2', '\x2', '\x2', '\xE2', '\xE3', '\v', '\x2', '\x2', '\x2', 
		'\xE3', 'P', '\x3', '\x2', '\x2', '\x2', '\r', '\x2', 'T', '\x88', '\x92', 
		'\x96', '\x9C', '\xB9', '\xC8', '\xCE', '\xD5', '\xD7', '\x3', '\x2', 
		'\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace InterpreterLib
