//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace InterpreterLib {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GLangParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		STRING=1, WHITESPACE=2, COMMA=3, TYPE_DELIMETER=4, BREAK=5, CONTINUE=6, 
		TYPE_NAME=7, BOOLEAN=8, DOUBLE=9, INTEGER=10, DECL_VARIABLE=11, IF=12, 
		ELSE=13, WHILE=14, FOR=15, FUNCTION=16, ASSIGNMENT_OPERATOR=17, ADDITIVE_OP=18, 
		MULTIPLICATIVE_OP=19, CARAT=20, LOW_PRIORITY_OP=21, COMPARE_OP=22, LOGICAL_OP=23, 
		BANG=24, IDENTIFIER=25, L_PARENTHESIS=26, R_PARENTHESIS=27, L_BRACE=28, 
		R_BRACE=29, UNKNOWN=30;
	public const int
		RULE_compilationUnit = 0, RULE_declerationOrAssign = 1, RULE_typeDefinition = 2, 
		RULE_globalStatement = 3, RULE_baseStatement = 4, RULE_statement = 5, 
		RULE_definedIdentifier = 6, RULE_seperatedDefinedIdentifier = 7, RULE_parametersDefinition = 8, 
		RULE_functionDefinition = 9, RULE_block = 10, RULE_expressionStatement = 11, 
		RULE_forStatement = 12, RULE_ifStatement = 13, RULE_whileStatement = 14, 
		RULE_variableDeclarationStatement = 15, RULE_assignmentExpression = 16, 
		RULE_literal = 17, RULE_unaryExpression = 18, RULE_binaryExpression = 19, 
		RULE_seperatedExpression = 20, RULE_functionCall = 21;
	public static readonly string[] ruleNames = {
		"compilationUnit", "declerationOrAssign", "typeDefinition", "globalStatement", 
		"baseStatement", "statement", "definedIdentifier", "seperatedDefinedIdentifier", 
		"parametersDefinition", "functionDefinition", "block", "expressionStatement", 
		"forStatement", "ifStatement", "whileStatement", "variableDeclarationStatement", 
		"assignmentExpression", "literal", "unaryExpression", "binaryExpression", 
		"seperatedExpression", "functionCall"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, "','", "':'", null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "'^'", null, null, null, 
		"'!'", null, "'('", "')'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "STRING", "WHITESPACE", "COMMA", "TYPE_DELIMETER", "BREAK", "CONTINUE", 
		"TYPE_NAME", "BOOLEAN", "DOUBLE", "INTEGER", "DECL_VARIABLE", "IF", "ELSE", 
		"WHILE", "FOR", "FUNCTION", "ASSIGNMENT_OPERATOR", "ADDITIVE_OP", "MULTIPLICATIVE_OP", 
		"CARAT", "LOW_PRIORITY_OP", "COMPARE_OP", "LOGICAL_OP", "BANG", "IDENTIFIER", 
		"L_PARENTHESIS", "R_PARENTHESIS", "L_BRACE", "R_BRACE", "UNKNOWN"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GLangParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public GLangParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public GLangParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class CompilationUnitContext : ParserRuleContext {
		public GlobalStatementContext[] globalStatement() {
			return GetRuleContexts<GlobalStatementContext>();
		}
		public GlobalStatementContext globalStatement(int i) {
			return GetRuleContext<GlobalStatementContext>(i);
		}
		public CompilationUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compilationUnit; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterCompilationUnit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitCompilationUnit(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompilationUnit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompilationUnitContext compilationUnit() {
		CompilationUnitContext _localctx = new CompilationUnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compilationUnit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 45;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 44; globalStatement();
				}
				}
				State = 47;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << BOOLEAN) | (1L << DOUBLE) | (1L << INTEGER) | (1L << DECL_VARIABLE) | (1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << FUNCTION) | (1L << ADDITIVE_OP) | (1L << BANG) | (1L << IDENTIFIER) | (1L << L_PARENTHESIS) | (1L << L_BRACE))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclerationOrAssignContext : ParserRuleContext {
		public VariableDeclarationStatementContext variableDeclarationStatement() {
			return GetRuleContext<VariableDeclarationStatementContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public DeclerationOrAssignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declerationOrAssign; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterDeclerationOrAssign(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitDeclerationOrAssign(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeclerationOrAssign(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclerationOrAssignContext declerationOrAssign() {
		DeclerationOrAssignContext _localctx = new DeclerationOrAssignContext(Context, State);
		EnterRule(_localctx, 2, RULE_declerationOrAssign);
		try {
			State = 51;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DECL_VARIABLE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 49; variableDeclarationStatement();
				}
				break;
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 50; assignmentExpression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeDefinitionContext : ParserRuleContext {
		public ITerminalNode TYPE_DELIMETER() { return GetToken(GLangParser.TYPE_DELIMETER, 0); }
		public ITerminalNode TYPE_NAME() { return GetToken(GLangParser.TYPE_NAME, 0); }
		public TypeDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterTypeDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitTypeDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeDefinitionContext typeDefinition() {
		TypeDefinitionContext _localctx = new TypeDefinitionContext(Context, State);
		EnterRule(_localctx, 4, RULE_typeDefinition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53; Match(TYPE_DELIMETER);
			State = 54; Match(TYPE_NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GlobalStatementContext : ParserRuleContext {
		public FunctionDefinitionContext functionDefinition() {
			return GetRuleContext<FunctionDefinitionContext>(0);
		}
		public BaseStatementContext baseStatement() {
			return GetRuleContext<BaseStatementContext>(0);
		}
		public GlobalStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_globalStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterGlobalStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitGlobalStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGlobalStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GlobalStatementContext globalStatement() {
		GlobalStatementContext _localctx = new GlobalStatementContext(Context, State);
		EnterRule(_localctx, 6, RULE_globalStatement);
		try {
			State = 58;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case FUNCTION:
				EnterOuterAlt(_localctx, 1);
				{
				State = 56; functionDefinition();
				}
				break;
			case STRING:
			case BOOLEAN:
			case DOUBLE:
			case INTEGER:
			case DECL_VARIABLE:
			case IF:
			case WHILE:
			case FOR:
			case ADDITIVE_OP:
			case BANG:
			case IDENTIFIER:
			case L_PARENTHESIS:
			case L_BRACE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 57; baseStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BaseStatementContext : ParserRuleContext {
		public ForStatementContext forStatement() {
			return GetRuleContext<ForStatementContext>(0);
		}
		public WhileStatementContext whileStatement() {
			return GetRuleContext<WhileStatementContext>(0);
		}
		public IfStatementContext ifStatement() {
			return GetRuleContext<IfStatementContext>(0);
		}
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public VariableDeclarationStatementContext variableDeclarationStatement() {
			return GetRuleContext<VariableDeclarationStatementContext>(0);
		}
		public ExpressionStatementContext expressionStatement() {
			return GetRuleContext<ExpressionStatementContext>(0);
		}
		public BaseStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_baseStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBaseStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBaseStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBaseStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BaseStatementContext baseStatement() {
		BaseStatementContext _localctx = new BaseStatementContext(Context, State);
		EnterRule(_localctx, 8, RULE_baseStatement);
		try {
			State = 66;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case FOR:
				EnterOuterAlt(_localctx, 1);
				{
				State = 60; forStatement();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 61; whileStatement();
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 3);
				{
				State = 62; ifStatement();
				}
				break;
			case L_BRACE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 63; block();
				}
				break;
			case DECL_VARIABLE:
				EnterOuterAlt(_localctx, 5);
				{
				State = 64; variableDeclarationStatement();
				}
				break;
			case STRING:
			case BOOLEAN:
			case DOUBLE:
			case INTEGER:
			case ADDITIVE_OP:
			case BANG:
			case IDENTIFIER:
			case L_PARENTHESIS:
				EnterOuterAlt(_localctx, 6);
				{
				State = 65; expressionStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public BaseStatementContext baseStatement() {
			return GetRuleContext<BaseStatementContext>(0);
		}
		public ITerminalNode BREAK() { return GetToken(GLangParser.BREAK, 0); }
		public ITerminalNode CONTINUE() { return GetToken(GLangParser.CONTINUE, 0); }
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 10, RULE_statement);
		try {
			State = 71;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
			case BOOLEAN:
			case DOUBLE:
			case INTEGER:
			case DECL_VARIABLE:
			case IF:
			case WHILE:
			case FOR:
			case ADDITIVE_OP:
			case BANG:
			case IDENTIFIER:
			case L_PARENTHESIS:
			case L_BRACE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 68; baseStatement();
				}
				break;
			case BREAK:
				EnterOuterAlt(_localctx, 2);
				{
				State = 69; Match(BREAK);
				}
				break;
			case CONTINUE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 70; Match(CONTINUE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefinedIdentifierContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public TypeDefinitionContext typeDefinition() {
			return GetRuleContext<TypeDefinitionContext>(0);
		}
		public DefinedIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_definedIdentifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterDefinedIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitDefinedIdentifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefinedIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefinedIdentifierContext definedIdentifier() {
		DefinedIdentifierContext _localctx = new DefinedIdentifierContext(Context, State);
		EnterRule(_localctx, 12, RULE_definedIdentifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 73; Match(IDENTIFIER);
			State = 74; typeDefinition();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SeperatedDefinedIdentifierContext : ParserRuleContext {
		public DefinedIdentifierContext definedIdentifier() {
			return GetRuleContext<DefinedIdentifierContext>(0);
		}
		public ITerminalNode COMMA() { return GetToken(GLangParser.COMMA, 0); }
		public SeperatedDefinedIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_seperatedDefinedIdentifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterSeperatedDefinedIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitSeperatedDefinedIdentifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSeperatedDefinedIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SeperatedDefinedIdentifierContext seperatedDefinedIdentifier() {
		SeperatedDefinedIdentifierContext _localctx = new SeperatedDefinedIdentifierContext(Context, State);
		EnterRule(_localctx, 14, RULE_seperatedDefinedIdentifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 76; definedIdentifier();
			State = 77; Match(COMMA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParametersDefinitionContext : ParserRuleContext {
		public DefinedIdentifierContext last;
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public DefinedIdentifierContext definedIdentifier() {
			return GetRuleContext<DefinedIdentifierContext>(0);
		}
		public SeperatedDefinedIdentifierContext[] seperatedDefinedIdentifier() {
			return GetRuleContexts<SeperatedDefinedIdentifierContext>();
		}
		public SeperatedDefinedIdentifierContext seperatedDefinedIdentifier(int i) {
			return GetRuleContext<SeperatedDefinedIdentifierContext>(i);
		}
		public ParametersDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parametersDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterParametersDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitParametersDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParametersDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParametersDefinitionContext parametersDefinition() {
		ParametersDefinitionContext _localctx = new ParametersDefinitionContext(Context, State);
		EnterRule(_localctx, 16, RULE_parametersDefinition);
		try {
			int _alt;
			State = 94;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 79; Match(L_PARENTHESIS);
				State = 81;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 80; seperatedDefinedIdentifier();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 83;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 85; _localctx.last = definedIdentifier();
				State = 86; Match(R_PARENTHESIS);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 88; Match(L_PARENTHESIS);
				State = 89; _localctx.last = definedIdentifier();
				State = 90; Match(R_PARENTHESIS);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 92; Match(L_PARENTHESIS);
				State = 93; Match(R_PARENTHESIS);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDefinitionContext : ParserRuleContext {
		public ITerminalNode FUNCTION() { return GetToken(GLangParser.FUNCTION, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ParametersDefinitionContext parametersDefinition() {
			return GetRuleContext<ParametersDefinitionContext>(0);
		}
		public TypeDefinitionContext typeDefinition() {
			return GetRuleContext<TypeDefinitionContext>(0);
		}
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public FunctionDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterFunctionDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitFunctionDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDefinitionContext functionDefinition() {
		FunctionDefinitionContext _localctx = new FunctionDefinitionContext(Context, State);
		EnterRule(_localctx, 18, RULE_functionDefinition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96; Match(FUNCTION);
			State = 97; Match(IDENTIFIER);
			State = 98; parametersDefinition();
			State = 99; typeDefinition();
			State = 100; statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public ITerminalNode L_BRACE() { return GetToken(GLangParser.L_BRACE, 0); }
		public ITerminalNode R_BRACE() { return GetToken(GLangParser.R_BRACE, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 20, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102; Match(L_BRACE);
			State = 106;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << BREAK) | (1L << CONTINUE) | (1L << BOOLEAN) | (1L << DOUBLE) | (1L << INTEGER) | (1L << DECL_VARIABLE) | (1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << ADDITIVE_OP) | (1L << BANG) | (1L << IDENTIFIER) | (1L << L_PARENTHESIS) | (1L << L_BRACE))) != 0)) {
				{
				{
				State = 103; statement();
				}
				}
				State = 108;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 109; Match(R_BRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionStatementContext : ParserRuleContext {
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ExpressionStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterExpressionStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitExpressionStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionStatementContext expressionStatement() {
		ExpressionStatementContext _localctx = new ExpressionStatementContext(Context, State);
		EnterRule(_localctx, 22, RULE_expressionStatement);
		try {
			State = 113;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 111; assignmentExpression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 112; binaryExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForStatementContext : ParserRuleContext {
		public ITerminalNode FOR() { return GetToken(GLangParser.FOR, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public DeclerationOrAssignContext declerationOrAssign() {
			return GetRuleContext<DeclerationOrAssignContext>(0);
		}
		public ITerminalNode[] COMMA() { return GetTokens(GLangParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(GLangParser.COMMA, i);
		}
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public ForStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterForStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitForStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitForStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ForStatementContext forStatement() {
		ForStatementContext _localctx = new ForStatementContext(Context, State);
		EnterRule(_localctx, 24, RULE_forStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 115; Match(FOR);
			State = 116; Match(L_PARENTHESIS);
			State = 117; declerationOrAssign();
			State = 118; Match(COMMA);
			State = 119; binaryExpression(0);
			State = 120; Match(COMMA);
			State = 121; assignmentExpression();
			State = 122; Match(R_PARENTHESIS);
			State = 123; statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementContext : ParserRuleContext {
		public StatementContext trueBranch;
		public StatementContext falseBranch;
		public ITerminalNode IF() { return GetToken(GLangParser.IF, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ITerminalNode ELSE() { return GetToken(GLangParser.ELSE, 0); }
		public IfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterIfStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitIfStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfStatementContext ifStatement() {
		IfStatementContext _localctx = new IfStatementContext(Context, State);
		EnterRule(_localctx, 26, RULE_ifStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125; Match(IF);
			State = 126; Match(L_PARENTHESIS);
			State = 127; binaryExpression(0);
			State = 128; Match(R_PARENTHESIS);
			State = 129; _localctx.trueBranch = statement();
			State = 132;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				{
				State = 130; Match(ELSE);
				State = 131; _localctx.falseBranch = statement();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileStatementContext : ParserRuleContext {
		public StatementContext body;
		public ITerminalNode WHILE() { return GetToken(GLangParser.WHILE, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public WhileStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterWhileStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitWhileStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhileStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhileStatementContext whileStatement() {
		WhileStatementContext _localctx = new WhileStatementContext(Context, State);
		EnterRule(_localctx, 28, RULE_whileStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 134; Match(WHILE);
			State = 135; Match(L_PARENTHESIS);
			State = 136; binaryExpression(0);
			State = 137; Match(R_PARENTHESIS);
			State = 138; _localctx.body = statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationStatementContext : ParserRuleContext {
		public ITerminalNode DECL_VARIABLE() { return GetToken(GLangParser.DECL_VARIABLE, 0); }
		public DefinedIdentifierContext definedIdentifier() {
			return GetRuleContext<DefinedIdentifierContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public VariableDeclarationStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclarationStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterVariableDeclarationStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitVariableDeclarationStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclarationStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationStatementContext variableDeclarationStatement() {
		VariableDeclarationStatementContext _localctx = new VariableDeclarationStatementContext(Context, State);
		EnterRule(_localctx, 30, RULE_variableDeclarationStatement);
		try {
			State = 144;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 140; Match(DECL_VARIABLE);
				State = 141; definedIdentifier();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 142; Match(DECL_VARIABLE);
				State = 143; assignmentExpression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentExpressionContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ITerminalNode ASSIGNMENT_OPERATOR() { return GetToken(GLangParser.ASSIGNMENT_OPERATOR, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public TypeDefinitionContext typeDefinition() {
			return GetRuleContext<TypeDefinitionContext>(0);
		}
		public AssignmentExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterAssignmentExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitAssignmentExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignmentExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentExpressionContext assignmentExpression() {
		AssignmentExpressionContext _localctx = new AssignmentExpressionContext(Context, State);
		EnterRule(_localctx, 32, RULE_assignmentExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146; Match(IDENTIFIER);
			State = 148;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TYPE_DELIMETER) {
				{
				State = 147; typeDefinition();
				}
			}

			State = 150; Match(ASSIGNMENT_OPERATOR);
			State = 151; binaryExpression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public ITerminalNode DOUBLE() { return GetToken(GLangParser.DOUBLE, 0); }
		public ITerminalNode INTEGER() { return GetToken(GLangParser.INTEGER, 0); }
		public ITerminalNode BOOLEAN() { return GetToken(GLangParser.BOOLEAN, 0); }
		public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ITerminalNode STRING() { return GetToken(GLangParser.STRING, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 34, RULE_literal);
		try {
			State = 159;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 153; Match(DOUBLE);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 154; Match(INTEGER);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 155; Match(BOOLEAN);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 156; functionCall();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 157; Match(IDENTIFIER);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 158; Match(STRING);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryExpressionContext : ParserRuleContext {
		public IToken op;
		public LiteralContext atom;
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public UnaryExpressionContext unaryExpression() {
			return GetRuleContext<UnaryExpressionContext>(0);
		}
		public ITerminalNode ADDITIVE_OP() { return GetToken(GLangParser.ADDITIVE_OP, 0); }
		public ITerminalNode BANG() { return GetToken(GLangParser.BANG, 0); }
		public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public UnaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterUnaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitUnaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryExpressionContext unaryExpression() {
		UnaryExpressionContext _localctx = new UnaryExpressionContext(Context, State);
		EnterRule(_localctx, 36, RULE_unaryExpression);
		int _la;
		try {
			State = 168;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case L_PARENTHESIS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 161; Match(L_PARENTHESIS);
				State = 162; binaryExpression(0);
				State = 163; Match(R_PARENTHESIS);
				}
				break;
			case ADDITIVE_OP:
			case BANG:
				EnterOuterAlt(_localctx, 2);
				{
				State = 165;
				_localctx.op = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==ADDITIVE_OP || _la==BANG) ) {
					_localctx.op = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 166; unaryExpression();
				}
				break;
			case STRING:
			case BOOLEAN:
			case DOUBLE:
			case INTEGER:
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 3);
				{
				State = 167; _localctx.atom = literal();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinaryExpressionContext : ParserRuleContext {
		public BinaryExpressionContext left;
		public UnaryExpressionContext atom;
		public IToken op;
		public BinaryExpressionContext right;
		public UnaryExpressionContext unaryExpression() {
			return GetRuleContext<UnaryExpressionContext>(0);
		}
		public BinaryExpressionContext[] binaryExpression() {
			return GetRuleContexts<BinaryExpressionContext>();
		}
		public BinaryExpressionContext binaryExpression(int i) {
			return GetRuleContext<BinaryExpressionContext>(i);
		}
		public ITerminalNode CARAT() { return GetToken(GLangParser.CARAT, 0); }
		public ITerminalNode MULTIPLICATIVE_OP() { return GetToken(GLangParser.MULTIPLICATIVE_OP, 0); }
		public ITerminalNode ADDITIVE_OP() { return GetToken(GLangParser.ADDITIVE_OP, 0); }
		public ITerminalNode LOW_PRIORITY_OP() { return GetToken(GLangParser.LOW_PRIORITY_OP, 0); }
		public ITerminalNode COMPARE_OP() { return GetToken(GLangParser.COMPARE_OP, 0); }
		public ITerminalNode LOGICAL_OP() { return GetToken(GLangParser.LOGICAL_OP, 0); }
		public BinaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBinaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBinaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BinaryExpressionContext binaryExpression() {
		return binaryExpression(0);
	}

	private BinaryExpressionContext binaryExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BinaryExpressionContext _localctx = new BinaryExpressionContext(Context, _parentState);
		BinaryExpressionContext _prevctx = _localctx;
		int _startState = 38;
		EnterRecursionRule(_localctx, 38, RULE_binaryExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 171; _localctx.atom = unaryExpression();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 193;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 191;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
					case 1:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 173;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 174; _localctx.op = Match(CARAT);
						State = 175; _localctx.right = binaryExpression(8);
						}
						break;
					case 2:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 176;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 177; _localctx.op = Match(MULTIPLICATIVE_OP);
						State = 178; _localctx.right = binaryExpression(7);
						}
						break;
					case 3:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 179;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 180; _localctx.op = Match(ADDITIVE_OP);
						State = 181; _localctx.right = binaryExpression(6);
						}
						break;
					case 4:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 182;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 183; _localctx.op = Match(LOW_PRIORITY_OP);
						State = 184; _localctx.right = binaryExpression(5);
						}
						break;
					case 5:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 185;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 186; _localctx.op = Match(COMPARE_OP);
						State = 187; _localctx.right = binaryExpression(4);
						}
						break;
					case 6:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 188;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 189; _localctx.op = Match(LOGICAL_OP);
						State = 190; _localctx.right = binaryExpression(3);
						}
						break;
					}
					} 
				}
				State = 195;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class SeperatedExpressionContext : ParserRuleContext {
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode COMMA() { return GetToken(GLangParser.COMMA, 0); }
		public SeperatedExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_seperatedExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterSeperatedExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitSeperatedExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSeperatedExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SeperatedExpressionContext seperatedExpression() {
		SeperatedExpressionContext _localctx = new SeperatedExpressionContext(Context, State);
		EnterRule(_localctx, 40, RULE_seperatedExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196; binaryExpression(0);
			State = 197; Match(COMMA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionCallContext : ParserRuleContext {
		public IToken funcName;
		public BinaryExpressionContext last;
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public SeperatedExpressionContext[] seperatedExpression() {
			return GetRuleContexts<SeperatedExpressionContext>();
		}
		public SeperatedExpressionContext seperatedExpression(int i) {
			return GetRuleContext<SeperatedExpressionContext>(i);
		}
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterFunctionCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitFunctionCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 42, RULE_functionCall);
		try {
			int _alt;
			State = 217;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 199; _localctx.funcName = Match(IDENTIFIER);
				State = 200; Match(L_PARENTHESIS);
				State = 202;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 201; seperatedExpression();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 204;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 206; _localctx.last = binaryExpression(0);
				State = 207; Match(R_PARENTHESIS);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 209; _localctx.funcName = Match(IDENTIFIER);
				State = 210; Match(L_PARENTHESIS);
				State = 211; _localctx.last = binaryExpression(0);
				State = 212; Match(R_PARENTHESIS);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 214; _localctx.funcName = Match(IDENTIFIER);
				State = 215; Match(L_PARENTHESIS);
				State = 216; Match(R_PARENTHESIS);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 19: return binaryExpression_sempred((BinaryExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool binaryExpression_sempred(BinaryExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 7);
		case 1: return Precpred(Context, 6);
		case 2: return Precpred(Context, 5);
		case 3: return Precpred(Context, 4);
		case 4: return Precpred(Context, 3);
		case 5: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', ' ', '\xDE', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x6', 
		'\x2', '\x30', '\n', '\x2', '\r', '\x2', '\xE', '\x2', '\x31', '\x3', 
		'\x3', '\x3', '\x3', '\x5', '\x3', '\x36', '\n', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 
		'=', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x45', '\n', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 'J', '\n', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x6', '\n', 'T', '\n', '\n', '\r', '\n', '\xE', '\n', 
		'U', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\x61', 
		'\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\a', '\f', 'k', '\n', '\f', 
		'\f', '\f', '\xE', '\f', 'n', '\v', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x5', '\r', 't', '\n', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x5', '\xF', '\x87', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\x93', '\n', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\x97', '\n', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', 
		'\xA2', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', '\xAB', 
		'\n', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\a', '\x15', '\xC2', '\n', '\x15', '\f', 
		'\x15', '\xE', '\x15', '\xC5', '\v', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x6', '\x17', 
		'\xCD', '\n', '\x17', '\r', '\x17', '\xE', '\x17', '\xCE', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x5', '\x17', '\xDC', '\n', '\x17', '\x3', '\x17', '\x2', '\x3', '(', 
		'\x18', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', 
		'*', ',', '\x2', '\x3', '\x4', '\x2', '\x14', '\x14', '\x1A', '\x1A', 
		'\x2', '\xE9', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x4', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x6', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\b', '<', '\x3', '\x2', '\x2', '\x2', '\n', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\f', 'I', '\x3', '\x2', '\x2', '\x2', '\xE', 'K', '\x3', '\x2', 
		'\x2', '\x2', '\x10', 'N', '\x3', '\x2', '\x2', '\x2', '\x12', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x14', '\x62', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'h', '\x3', '\x2', '\x2', '\x2', '\x18', 's', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', 'u', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x7F', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\x88', '\x3', '\x2', '\x2', '\x2', ' ', '\x92', 
		'\x3', '\x2', '\x2', '\x2', '\"', '\x94', '\x3', '\x2', '\x2', '\x2', 
		'$', '\xA1', '\x3', '\x2', '\x2', '\x2', '&', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '(', '\xAC', '\x3', '\x2', '\x2', '\x2', '*', '\xC6', '\x3', '\x2', 
		'\x2', '\x2', ',', '\xDB', '\x3', '\x2', '\x2', '\x2', '.', '\x30', '\x5', 
		'\b', '\x5', '\x2', '/', '.', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '/', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\x32', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x36', '\x5', ' ', '\x11', '\x2', '\x34', '\x36', '\x5', 
		'\"', '\x12', '\x2', '\x35', '\x33', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\x34', '\x3', '\x2', '\x2', '\x2', '\x36', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x37', '\x38', '\a', '\x6', '\x2', '\x2', '\x38', '\x39', '\a', 
		'\t', '\x2', '\x2', '\x39', '\a', '\x3', '\x2', '\x2', '\x2', ':', '=', 
		'\x5', '\x14', '\v', '\x2', ';', '=', '\x5', '\n', '\x6', '\x2', '<', 
		':', '\x3', '\x2', '\x2', '\x2', '<', ';', '\x3', '\x2', '\x2', '\x2', 
		'=', '\t', '\x3', '\x2', '\x2', '\x2', '>', '\x45', '\x5', '\x1A', '\xE', 
		'\x2', '?', '\x45', '\x5', '\x1E', '\x10', '\x2', '@', '\x45', '\x5', 
		'\x1C', '\xF', '\x2', '\x41', '\x45', '\x5', '\x16', '\f', '\x2', '\x42', 
		'\x45', '\x5', ' ', '\x11', '\x2', '\x43', '\x45', '\x5', '\x18', '\r', 
		'\x2', '\x44', '>', '\x3', '\x2', '\x2', '\x2', '\x44', '?', '\x3', '\x2', 
		'\x2', '\x2', '\x44', '@', '\x3', '\x2', '\x2', '\x2', '\x44', '\x41', 
		'\x3', '\x2', '\x2', '\x2', '\x44', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\x44', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x46', 'J', '\x5', '\n', '\x6', '\x2', 'G', 'J', '\a', 
		'\a', '\x2', '\x2', 'H', 'J', '\a', '\b', '\x2', '\x2', 'I', '\x46', '\x3', 
		'\x2', '\x2', '\x2', 'I', 'G', '\x3', '\x2', '\x2', '\x2', 'I', 'H', '\x3', 
		'\x2', '\x2', '\x2', 'J', '\r', '\x3', '\x2', '\x2', '\x2', 'K', 'L', 
		'\a', '\x1B', '\x2', '\x2', 'L', 'M', '\x5', '\x6', '\x4', '\x2', 'M', 
		'\xF', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\x5', '\xE', '\b', '\x2', 
		'O', 'P', '\a', '\x5', '\x2', '\x2', 'P', '\x11', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'S', '\a', '\x1C', '\x2', '\x2', 'R', 'T', '\x5', '\x10', 
		'\t', '\x2', 'S', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x5', '\xE', 
		'\b', '\x2', 'X', 'Y', '\a', '\x1D', '\x2', '\x2', 'Y', '\x61', '\x3', 
		'\x2', '\x2', '\x2', 'Z', '[', '\a', '\x1C', '\x2', '\x2', '[', '\\', 
		'\x5', '\xE', '\b', '\x2', '\\', ']', '\a', '\x1D', '\x2', '\x2', ']', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', '\x1C', '\x2', '\x2', 
		'_', '\x61', '\a', '\x1D', '\x2', '\x2', '`', 'Q', '\x3', '\x2', '\x2', 
		'\x2', '`', 'Z', '\x3', '\x2', '\x2', '\x2', '`', '^', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '\x13', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\a', 
		'\x12', '\x2', '\x2', '\x63', '\x64', '\a', '\x1B', '\x2', '\x2', '\x64', 
		'\x65', '\x5', '\x12', '\n', '\x2', '\x65', '\x66', '\x5', '\x6', '\x4', 
		'\x2', '\x66', 'g', '\x5', '\f', '\a', '\x2', 'g', '\x15', '\x3', '\x2', 
		'\x2', '\x2', 'h', 'l', '\a', '\x1E', '\x2', '\x2', 'i', 'k', '\x5', '\f', 
		'\a', '\x2', 'j', 'i', '\x3', '\x2', '\x2', '\x2', 'k', 'n', '\x3', '\x2', 
		'\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\x3', '\x2', 
		'\x2', '\x2', 'm', 'o', '\x3', '\x2', '\x2', '\x2', 'n', 'l', '\x3', '\x2', 
		'\x2', '\x2', 'o', 'p', '\a', '\x1F', '\x2', '\x2', 'p', '\x17', '\x3', 
		'\x2', '\x2', '\x2', 'q', 't', '\x5', '\"', '\x12', '\x2', 'r', 't', '\x5', 
		'(', '\x15', '\x2', 's', 'q', '\x3', '\x2', '\x2', '\x2', 's', 'r', '\x3', 
		'\x2', '\x2', '\x2', 't', '\x19', '\x3', '\x2', '\x2', '\x2', 'u', 'v', 
		'\a', '\x11', '\x2', '\x2', 'v', 'w', '\a', '\x1C', '\x2', '\x2', 'w', 
		'x', '\x5', '\x4', '\x3', '\x2', 'x', 'y', '\a', '\x5', '\x2', '\x2', 
		'y', 'z', '\x5', '(', '\x15', '\x2', 'z', '{', '\a', '\x5', '\x2', '\x2', 
		'{', '|', '\x5', '\"', '\x12', '\x2', '|', '}', '\a', '\x1D', '\x2', '\x2', 
		'}', '~', '\x5', '\f', '\a', '\x2', '~', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x80', '\a', '\xE', '\x2', '\x2', '\x80', '\x81', '\a', 
		'\x1C', '\x2', '\x2', '\x81', '\x82', '\x5', '(', '\x15', '\x2', '\x82', 
		'\x83', '\a', '\x1D', '\x2', '\x2', '\x83', '\x86', '\x5', '\f', '\a', 
		'\x2', '\x84', '\x85', '\a', '\xF', '\x2', '\x2', '\x85', '\x87', '\x5', 
		'\f', '\a', '\x2', '\x86', '\x84', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x87', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x88', '\x89', '\a', '\x10', '\x2', '\x2', '\x89', '\x8A', '\a', 
		'\x1C', '\x2', '\x2', '\x8A', '\x8B', '\x5', '(', '\x15', '\x2', '\x8B', 
		'\x8C', '\a', '\x1D', '\x2', '\x2', '\x8C', '\x8D', '\x5', '\f', '\a', 
		'\x2', '\x8D', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', 
		'\r', '\x2', '\x2', '\x8F', '\x93', '\x5', '\xE', '\b', '\x2', '\x90', 
		'\x91', '\a', '\r', '\x2', '\x2', '\x91', '\x93', '\x5', '\"', '\x12', 
		'\x2', '\x92', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x92', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '!', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x96', '\a', '\x1B', '\x2', '\x2', '\x95', '\x97', '\x5', '\x6', '\x4', 
		'\x2', '\x96', '\x95', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x99', '\a', '\x13', '\x2', '\x2', '\x99', '\x9A', '\x5', '(', '\x15', 
		'\x2', '\x9A', '#', '\x3', '\x2', '\x2', '\x2', '\x9B', '\xA2', '\a', 
		'\v', '\x2', '\x2', '\x9C', '\xA2', '\a', '\f', '\x2', '\x2', '\x9D', 
		'\xA2', '\a', '\n', '\x2', '\x2', '\x9E', '\xA2', '\x5', ',', '\x17', 
		'\x2', '\x9F', '\xA2', '\a', '\x1B', '\x2', '\x2', '\xA0', '\xA2', '\a', 
		'\x3', '\x2', '\x2', '\xA1', '\x9B', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'%', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\a', '\x1C', '\x2', 
		'\x2', '\xA4', '\xA5', '\x5', '(', '\x15', '\x2', '\xA5', '\xA6', '\a', 
		'\x1D', '\x2', '\x2', '\xA6', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'\xA8', '\t', '\x2', '\x2', '\x2', '\xA8', '\xAB', '\x5', '&', '\x14', 
		'\x2', '\xA9', '\xAB', '\x5', '$', '\x13', '\x2', '\xAA', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\xAA', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xA9', '\x3', '\x2', '\x2', '\x2', '\xAB', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAD', '\b', '\x15', '\x1', '\x2', '\xAD', '\xAE', '\x5', 
		'&', '\x14', '\x2', '\xAE', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xB0', '\f', '\t', '\x2', '\x2', '\xB0', '\xB1', '\a', '\x16', '\x2', 
		'\x2', '\xB1', '\xC2', '\x5', '(', '\x15', '\n', '\xB2', '\xB3', '\f', 
		'\b', '\x2', '\x2', '\xB3', '\xB4', '\a', '\x15', '\x2', '\x2', '\xB4', 
		'\xC2', '\x5', '(', '\x15', '\t', '\xB5', '\xB6', '\f', '\a', '\x2', '\x2', 
		'\xB6', '\xB7', '\a', '\x14', '\x2', '\x2', '\xB7', '\xC2', '\x5', '(', 
		'\x15', '\b', '\xB8', '\xB9', '\f', '\x6', '\x2', '\x2', '\xB9', '\xBA', 
		'\a', '\x17', '\x2', '\x2', '\xBA', '\xC2', '\x5', '(', '\x15', '\a', 
		'\xBB', '\xBC', '\f', '\x5', '\x2', '\x2', '\xBC', '\xBD', '\a', '\x18', 
		'\x2', '\x2', '\xBD', '\xC2', '\x5', '(', '\x15', '\x6', '\xBE', '\xBF', 
		'\f', '\x4', '\x2', '\x2', '\xBF', '\xC0', '\a', '\x19', '\x2', '\x2', 
		'\xC0', '\xC2', '\x5', '(', '\x15', '\x5', '\xC1', '\xAF', '\x3', '\x2', 
		'\x2', '\x2', '\xC1', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xB5', 
		'\x3', '\x2', '\x2', '\x2', '\xC1', '\xB8', '\x3', '\x2', '\x2', '\x2', 
		'\xC1', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xBE', '\x3', '\x2', 
		'\x2', '\x2', '\xC2', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC1', 
		'\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', '\x2', '\x2', '\x2', 
		'\xC4', ')', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', 
		'\x2', '\x2', '\xC6', '\xC7', '\x5', '(', '\x15', '\x2', '\xC7', '\xC8', 
		'\a', '\x5', '\x2', '\x2', '\xC8', '+', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'\xCA', '\a', '\x1B', '\x2', '\x2', '\xCA', '\xCC', '\a', '\x1C', '\x2', 
		'\x2', '\xCB', '\xCD', '\x5', '*', '\x16', '\x2', '\xCC', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xCE', 
		'\xCC', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCF', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', '\x5', 
		'(', '\x15', '\x2', '\xD1', '\xD2', '\a', '\x1D', '\x2', '\x2', '\xD2', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\a', '\x1B', '\x2', 
		'\x2', '\xD4', '\xD5', '\a', '\x1C', '\x2', '\x2', '\xD5', '\xD6', '\x5', 
		'(', '\x15', '\x2', '\xD6', '\xD7', '\a', '\x1D', '\x2', '\x2', '\xD7', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD9', '\a', '\x1B', '\x2', 
		'\x2', '\xD9', '\xDA', '\a', '\x1C', '\x2', '\x2', '\xDA', '\xDC', '\a', 
		'\x1D', '\x2', '\x2', '\xDB', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xDB', 
		'\xD3', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xD8', '\x3', '\x2', '\x2', 
		'\x2', '\xDC', '-', '\x3', '\x2', '\x2', '\x2', '\x14', '\x31', '\x35', 
		'<', '\x44', 'I', 'U', '`', 'l', 's', '\x86', '\x92', '\x96', '\xA1', 
		'\xAA', '\xC1', '\xC3', '\xCE', '\xDB',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace InterpreterLib
