//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace InterpreterLib {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GLangParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		STRING=1, WHITESPACE=2, COMMA=3, TYPE_DELIMETER=4, TYPE_NAME=5, BOOLEAN=6, 
		DOUBLE=7, INTEGER=8, DECL_VARIABLE=9, IF=10, ELSE=11, WHILE=12, FOR=13, 
		FUNCTION=14, ASSIGNMENT_OPERATOR=15, ADDITIVE_OP=16, MULTIPLICATIVE_OP=17, 
		CARAT=18, LOW_PRIORITY_OP=19, COMPARE_OP=20, LOGICAL_OP=21, BANG=22, IDENTIFIER=23, 
		L_PARENTHESIS=24, R_PARENTHESIS=25, L_BRACE=26, R_BRACE=27;
	public const int
		RULE_compilationUnit = 0, RULE_declerationOrAssign = 1, RULE_typeDefinition = 2, 
		RULE_globalStatement = 3, RULE_statement = 4, RULE_definedIdentifier = 5, 
		RULE_seperatedDefinedIdentifier = 6, RULE_parametersDefinition = 7, RULE_functionDefinition = 8, 
		RULE_block = 9, RULE_expressionStatement = 10, RULE_forStatement = 11, 
		RULE_ifStatement = 12, RULE_whileStatement = 13, RULE_variableDeclarationStatement = 14, 
		RULE_assignmentExpression = 15, RULE_literal = 16, RULE_unaryExpression = 17, 
		RULE_binaryExpression = 18, RULE_seperatedExpression = 19, RULE_functionCall = 20;
	public static readonly string[] ruleNames = {
		"compilationUnit", "declerationOrAssign", "typeDefinition", "globalStatement", 
		"statement", "definedIdentifier", "seperatedDefinedIdentifier", "parametersDefinition", 
		"functionDefinition", "block", "expressionStatement", "forStatement", 
		"ifStatement", "whileStatement", "variableDeclarationStatement", "assignmentExpression", 
		"literal", "unaryExpression", "binaryExpression", "seperatedExpression", 
		"functionCall"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, "','", "':'", null, null, null, null, null, "'if'", 
		"'else'", "'while'", "'for'", "'function'", null, null, null, "'^'", null, 
		null, null, "'!'", null, "'('", "')'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "STRING", "WHITESPACE", "COMMA", "TYPE_DELIMETER", "TYPE_NAME", 
		"BOOLEAN", "DOUBLE", "INTEGER", "DECL_VARIABLE", "IF", "ELSE", "WHILE", 
		"FOR", "FUNCTION", "ASSIGNMENT_OPERATOR", "ADDITIVE_OP", "MULTIPLICATIVE_OP", 
		"CARAT", "LOW_PRIORITY_OP", "COMPARE_OP", "LOGICAL_OP", "BANG", "IDENTIFIER", 
		"L_PARENTHESIS", "R_PARENTHESIS", "L_BRACE", "R_BRACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GLangParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public GLangParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public GLangParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class CompilationUnitContext : ParserRuleContext {
		public GlobalStatementContext[] globalStatement() {
			return GetRuleContexts<GlobalStatementContext>();
		}
		public GlobalStatementContext globalStatement(int i) {
			return GetRuleContext<GlobalStatementContext>(i);
		}
		public CompilationUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compilationUnit; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterCompilationUnit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitCompilationUnit(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompilationUnit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompilationUnitContext compilationUnit() {
		CompilationUnitContext _localctx = new CompilationUnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compilationUnit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 43;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 42; globalStatement();
				}
				}
				State = 45;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << BOOLEAN) | (1L << DOUBLE) | (1L << INTEGER) | (1L << DECL_VARIABLE) | (1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << FUNCTION) | (1L << ADDITIVE_OP) | (1L << BANG) | (1L << IDENTIFIER) | (1L << L_PARENTHESIS) | (1L << L_BRACE))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclerationOrAssignContext : ParserRuleContext {
		public VariableDeclarationStatementContext variableDeclarationStatement() {
			return GetRuleContext<VariableDeclarationStatementContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public DeclerationOrAssignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declerationOrAssign; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterDeclerationOrAssign(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitDeclerationOrAssign(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeclerationOrAssign(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclerationOrAssignContext declerationOrAssign() {
		DeclerationOrAssignContext _localctx = new DeclerationOrAssignContext(Context, State);
		EnterRule(_localctx, 2, RULE_declerationOrAssign);
		try {
			State = 49;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DECL_VARIABLE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 47; variableDeclarationStatement();
				}
				break;
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 48; assignmentExpression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeDefinitionContext : ParserRuleContext {
		public ITerminalNode TYPE_DELIMETER() { return GetToken(GLangParser.TYPE_DELIMETER, 0); }
		public ITerminalNode TYPE_NAME() { return GetToken(GLangParser.TYPE_NAME, 0); }
		public TypeDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterTypeDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitTypeDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeDefinitionContext typeDefinition() {
		TypeDefinitionContext _localctx = new TypeDefinitionContext(Context, State);
		EnterRule(_localctx, 4, RULE_typeDefinition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51; Match(TYPE_DELIMETER);
			State = 52; Match(TYPE_NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GlobalStatementContext : ParserRuleContext {
		public FunctionDefinitionContext functionDefinition() {
			return GetRuleContext<FunctionDefinitionContext>(0);
		}
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public GlobalStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_globalStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterGlobalStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitGlobalStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGlobalStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GlobalStatementContext globalStatement() {
		GlobalStatementContext _localctx = new GlobalStatementContext(Context, State);
		EnterRule(_localctx, 6, RULE_globalStatement);
		try {
			State = 56;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case FUNCTION:
				EnterOuterAlt(_localctx, 1);
				{
				State = 54; functionDefinition();
				}
				break;
			case STRING:
			case BOOLEAN:
			case DOUBLE:
			case INTEGER:
			case DECL_VARIABLE:
			case IF:
			case WHILE:
			case FOR:
			case ADDITIVE_OP:
			case BANG:
			case IDENTIFIER:
			case L_PARENTHESIS:
			case L_BRACE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 55; statement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public ForStatementContext forStatement() {
			return GetRuleContext<ForStatementContext>(0);
		}
		public WhileStatementContext whileStatement() {
			return GetRuleContext<WhileStatementContext>(0);
		}
		public IfStatementContext ifStatement() {
			return GetRuleContext<IfStatementContext>(0);
		}
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public VariableDeclarationStatementContext variableDeclarationStatement() {
			return GetRuleContext<VariableDeclarationStatementContext>(0);
		}
		public ExpressionStatementContext expressionStatement() {
			return GetRuleContext<ExpressionStatementContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 8, RULE_statement);
		try {
			State = 64;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case FOR:
				EnterOuterAlt(_localctx, 1);
				{
				State = 58; forStatement();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 59; whileStatement();
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 3);
				{
				State = 60; ifStatement();
				}
				break;
			case L_BRACE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 61; block();
				}
				break;
			case DECL_VARIABLE:
				EnterOuterAlt(_localctx, 5);
				{
				State = 62; variableDeclarationStatement();
				}
				break;
			case STRING:
			case BOOLEAN:
			case DOUBLE:
			case INTEGER:
			case ADDITIVE_OP:
			case BANG:
			case IDENTIFIER:
			case L_PARENTHESIS:
				EnterOuterAlt(_localctx, 6);
				{
				State = 63; expressionStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefinedIdentifierContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public TypeDefinitionContext typeDefinition() {
			return GetRuleContext<TypeDefinitionContext>(0);
		}
		public DefinedIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_definedIdentifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterDefinedIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitDefinedIdentifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefinedIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefinedIdentifierContext definedIdentifier() {
		DefinedIdentifierContext _localctx = new DefinedIdentifierContext(Context, State);
		EnterRule(_localctx, 10, RULE_definedIdentifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66; Match(IDENTIFIER);
			State = 67; typeDefinition();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SeperatedDefinedIdentifierContext : ParserRuleContext {
		public DefinedIdentifierContext definedIdentifier() {
			return GetRuleContext<DefinedIdentifierContext>(0);
		}
		public ITerminalNode COMMA() { return GetToken(GLangParser.COMMA, 0); }
		public SeperatedDefinedIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_seperatedDefinedIdentifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterSeperatedDefinedIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitSeperatedDefinedIdentifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSeperatedDefinedIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SeperatedDefinedIdentifierContext seperatedDefinedIdentifier() {
		SeperatedDefinedIdentifierContext _localctx = new SeperatedDefinedIdentifierContext(Context, State);
		EnterRule(_localctx, 12, RULE_seperatedDefinedIdentifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69; definedIdentifier();
			State = 70; Match(COMMA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParametersDefinitionContext : ParserRuleContext {
		public DefinedIdentifierContext last;
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public DefinedIdentifierContext definedIdentifier() {
			return GetRuleContext<DefinedIdentifierContext>(0);
		}
		public SeperatedDefinedIdentifierContext[] seperatedDefinedIdentifier() {
			return GetRuleContexts<SeperatedDefinedIdentifierContext>();
		}
		public SeperatedDefinedIdentifierContext seperatedDefinedIdentifier(int i) {
			return GetRuleContext<SeperatedDefinedIdentifierContext>(i);
		}
		public ParametersDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parametersDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterParametersDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitParametersDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParametersDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParametersDefinitionContext parametersDefinition() {
		ParametersDefinitionContext _localctx = new ParametersDefinitionContext(Context, State);
		EnterRule(_localctx, 14, RULE_parametersDefinition);
		try {
			int _alt;
			State = 87;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 72; Match(L_PARENTHESIS);
				State = 74;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 73; seperatedDefinedIdentifier();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 76;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 78; _localctx.last = definedIdentifier();
				State = 79; Match(R_PARENTHESIS);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 81; Match(L_PARENTHESIS);
				State = 82; _localctx.last = definedIdentifier();
				State = 83; Match(R_PARENTHESIS);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 85; Match(L_PARENTHESIS);
				State = 86; Match(R_PARENTHESIS);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDefinitionContext : ParserRuleContext {
		public ITerminalNode FUNCTION() { return GetToken(GLangParser.FUNCTION, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ParametersDefinitionContext parametersDefinition() {
			return GetRuleContext<ParametersDefinitionContext>(0);
		}
		public TypeDefinitionContext typeDefinition() {
			return GetRuleContext<TypeDefinitionContext>(0);
		}
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public FunctionDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterFunctionDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitFunctionDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDefinitionContext functionDefinition() {
		FunctionDefinitionContext _localctx = new FunctionDefinitionContext(Context, State);
		EnterRule(_localctx, 16, RULE_functionDefinition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 89; Match(FUNCTION);
			State = 90; Match(IDENTIFIER);
			State = 91; parametersDefinition();
			State = 92; typeDefinition();
			State = 93; statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public ITerminalNode L_BRACE() { return GetToken(GLangParser.L_BRACE, 0); }
		public ITerminalNode R_BRACE() { return GetToken(GLangParser.R_BRACE, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 18, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95; Match(L_BRACE);
			State = 99;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << BOOLEAN) | (1L << DOUBLE) | (1L << INTEGER) | (1L << DECL_VARIABLE) | (1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << ADDITIVE_OP) | (1L << BANG) | (1L << IDENTIFIER) | (1L << L_PARENTHESIS) | (1L << L_BRACE))) != 0)) {
				{
				{
				State = 96; statement();
				}
				}
				State = 101;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 102; Match(R_BRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionStatementContext : ParserRuleContext {
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ExpressionStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterExpressionStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitExpressionStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionStatementContext expressionStatement() {
		ExpressionStatementContext _localctx = new ExpressionStatementContext(Context, State);
		EnterRule(_localctx, 20, RULE_expressionStatement);
		try {
			State = 106;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 104; assignmentExpression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 105; binaryExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForStatementContext : ParserRuleContext {
		public ITerminalNode FOR() { return GetToken(GLangParser.FOR, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public DeclerationOrAssignContext declerationOrAssign() {
			return GetRuleContext<DeclerationOrAssignContext>(0);
		}
		public ITerminalNode[] COMMA() { return GetTokens(GLangParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(GLangParser.COMMA, i);
		}
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public ForStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterForStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitForStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitForStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ForStatementContext forStatement() {
		ForStatementContext _localctx = new ForStatementContext(Context, State);
		EnterRule(_localctx, 22, RULE_forStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108; Match(FOR);
			State = 109; Match(L_PARENTHESIS);
			State = 110; declerationOrAssign();
			State = 111; Match(COMMA);
			State = 112; binaryExpression(0);
			State = 113; Match(COMMA);
			State = 114; assignmentExpression();
			State = 115; Match(R_PARENTHESIS);
			State = 116; statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementContext : ParserRuleContext {
		public StatementContext trueBranch;
		public StatementContext falseBranch;
		public ITerminalNode IF() { return GetToken(GLangParser.IF, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ITerminalNode ELSE() { return GetToken(GLangParser.ELSE, 0); }
		public IfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterIfStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitIfStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfStatementContext ifStatement() {
		IfStatementContext _localctx = new IfStatementContext(Context, State);
		EnterRule(_localctx, 24, RULE_ifStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118; Match(IF);
			State = 119; Match(L_PARENTHESIS);
			State = 120; binaryExpression(0);
			State = 121; Match(R_PARENTHESIS);
			State = 122; _localctx.trueBranch = statement();
			State = 125;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				{
				State = 123; Match(ELSE);
				State = 124; _localctx.falseBranch = statement();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileStatementContext : ParserRuleContext {
		public StatementContext body;
		public ITerminalNode WHILE() { return GetToken(GLangParser.WHILE, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public WhileStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterWhileStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitWhileStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhileStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhileStatementContext whileStatement() {
		WhileStatementContext _localctx = new WhileStatementContext(Context, State);
		EnterRule(_localctx, 26, RULE_whileStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127; Match(WHILE);
			State = 128; Match(L_PARENTHESIS);
			State = 129; binaryExpression(0);
			State = 130; Match(R_PARENTHESIS);
			State = 131; _localctx.body = statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationStatementContext : ParserRuleContext {
		public ITerminalNode DECL_VARIABLE() { return GetToken(GLangParser.DECL_VARIABLE, 0); }
		public DefinedIdentifierContext definedIdentifier() {
			return GetRuleContext<DefinedIdentifierContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public VariableDeclarationStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclarationStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterVariableDeclarationStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitVariableDeclarationStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclarationStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationStatementContext variableDeclarationStatement() {
		VariableDeclarationStatementContext _localctx = new VariableDeclarationStatementContext(Context, State);
		EnterRule(_localctx, 28, RULE_variableDeclarationStatement);
		try {
			State = 137;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 133; Match(DECL_VARIABLE);
				State = 134; definedIdentifier();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 135; Match(DECL_VARIABLE);
				State = 136; assignmentExpression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentExpressionContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ITerminalNode ASSIGNMENT_OPERATOR() { return GetToken(GLangParser.ASSIGNMENT_OPERATOR, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public TypeDefinitionContext typeDefinition() {
			return GetRuleContext<TypeDefinitionContext>(0);
		}
		public AssignmentExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterAssignmentExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitAssignmentExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignmentExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentExpressionContext assignmentExpression() {
		AssignmentExpressionContext _localctx = new AssignmentExpressionContext(Context, State);
		EnterRule(_localctx, 30, RULE_assignmentExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139; Match(IDENTIFIER);
			State = 141;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TYPE_DELIMETER) {
				{
				State = 140; typeDefinition();
				}
			}

			State = 143; Match(ASSIGNMENT_OPERATOR);
			State = 144; binaryExpression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public ITerminalNode DOUBLE() { return GetToken(GLangParser.DOUBLE, 0); }
		public ITerminalNode INTEGER() { return GetToken(GLangParser.INTEGER, 0); }
		public ITerminalNode BOOLEAN() { return GetToken(GLangParser.BOOLEAN, 0); }
		public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ITerminalNode STRING() { return GetToken(GLangParser.STRING, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 32, RULE_literal);
		try {
			State = 152;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 146; Match(DOUBLE);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 147; Match(INTEGER);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 148; Match(BOOLEAN);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 149; functionCall();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 150; Match(IDENTIFIER);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 151; Match(STRING);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryExpressionContext : ParserRuleContext {
		public IToken op;
		public LiteralContext atom;
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public UnaryExpressionContext unaryExpression() {
			return GetRuleContext<UnaryExpressionContext>(0);
		}
		public ITerminalNode ADDITIVE_OP() { return GetToken(GLangParser.ADDITIVE_OP, 0); }
		public ITerminalNode BANG() { return GetToken(GLangParser.BANG, 0); }
		public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public UnaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterUnaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitUnaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryExpressionContext unaryExpression() {
		UnaryExpressionContext _localctx = new UnaryExpressionContext(Context, State);
		EnterRule(_localctx, 34, RULE_unaryExpression);
		int _la;
		try {
			State = 161;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case L_PARENTHESIS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 154; Match(L_PARENTHESIS);
				State = 155; binaryExpression(0);
				State = 156; Match(R_PARENTHESIS);
				}
				break;
			case ADDITIVE_OP:
			case BANG:
				EnterOuterAlt(_localctx, 2);
				{
				State = 158;
				_localctx.op = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==ADDITIVE_OP || _la==BANG) ) {
					_localctx.op = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 159; unaryExpression();
				}
				break;
			case STRING:
			case BOOLEAN:
			case DOUBLE:
			case INTEGER:
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 3);
				{
				State = 160; _localctx.atom = literal();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinaryExpressionContext : ParserRuleContext {
		public BinaryExpressionContext left;
		public UnaryExpressionContext atom;
		public IToken op;
		public BinaryExpressionContext right;
		public UnaryExpressionContext unaryExpression() {
			return GetRuleContext<UnaryExpressionContext>(0);
		}
		public BinaryExpressionContext[] binaryExpression() {
			return GetRuleContexts<BinaryExpressionContext>();
		}
		public BinaryExpressionContext binaryExpression(int i) {
			return GetRuleContext<BinaryExpressionContext>(i);
		}
		public ITerminalNode CARAT() { return GetToken(GLangParser.CARAT, 0); }
		public ITerminalNode MULTIPLICATIVE_OP() { return GetToken(GLangParser.MULTIPLICATIVE_OP, 0); }
		public ITerminalNode ADDITIVE_OP() { return GetToken(GLangParser.ADDITIVE_OP, 0); }
		public ITerminalNode LOW_PRIORITY_OP() { return GetToken(GLangParser.LOW_PRIORITY_OP, 0); }
		public ITerminalNode COMPARE_OP() { return GetToken(GLangParser.COMPARE_OP, 0); }
		public ITerminalNode LOGICAL_OP() { return GetToken(GLangParser.LOGICAL_OP, 0); }
		public BinaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBinaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBinaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BinaryExpressionContext binaryExpression() {
		return binaryExpression(0);
	}

	private BinaryExpressionContext binaryExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BinaryExpressionContext _localctx = new BinaryExpressionContext(Context, _parentState);
		BinaryExpressionContext _prevctx = _localctx;
		int _startState = 36;
		EnterRecursionRule(_localctx, 36, RULE_binaryExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 164; _localctx.atom = unaryExpression();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 186;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 184;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
					case 1:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 166;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 167; _localctx.op = Match(CARAT);
						State = 168; _localctx.right = binaryExpression(8);
						}
						break;
					case 2:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 169;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 170; _localctx.op = Match(MULTIPLICATIVE_OP);
						State = 171; _localctx.right = binaryExpression(7);
						}
						break;
					case 3:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 172;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 173; _localctx.op = Match(ADDITIVE_OP);
						State = 174; _localctx.right = binaryExpression(6);
						}
						break;
					case 4:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 175;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 176; _localctx.op = Match(LOW_PRIORITY_OP);
						State = 177; _localctx.right = binaryExpression(5);
						}
						break;
					case 5:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 178;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 179; _localctx.op = Match(COMPARE_OP);
						State = 180; _localctx.right = binaryExpression(4);
						}
						break;
					case 6:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 181;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 182; _localctx.op = Match(LOGICAL_OP);
						State = 183; _localctx.right = binaryExpression(3);
						}
						break;
					}
					} 
				}
				State = 188;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class SeperatedExpressionContext : ParserRuleContext {
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode COMMA() { return GetToken(GLangParser.COMMA, 0); }
		public SeperatedExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_seperatedExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterSeperatedExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitSeperatedExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSeperatedExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SeperatedExpressionContext seperatedExpression() {
		SeperatedExpressionContext _localctx = new SeperatedExpressionContext(Context, State);
		EnterRule(_localctx, 38, RULE_seperatedExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 189; binaryExpression(0);
			State = 190; Match(COMMA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionCallContext : ParserRuleContext {
		public IToken funcName;
		public BinaryExpressionContext last;
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public SeperatedExpressionContext[] seperatedExpression() {
			return GetRuleContexts<SeperatedExpressionContext>();
		}
		public SeperatedExpressionContext seperatedExpression(int i) {
			return GetRuleContext<SeperatedExpressionContext>(i);
		}
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterFunctionCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitFunctionCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 40, RULE_functionCall);
		try {
			int _alt;
			State = 210;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 192; _localctx.funcName = Match(IDENTIFIER);
				State = 193; Match(L_PARENTHESIS);
				State = 195;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 194; seperatedExpression();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 197;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 199; _localctx.last = binaryExpression(0);
				State = 200; Match(R_PARENTHESIS);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 202; _localctx.funcName = Match(IDENTIFIER);
				State = 203; Match(L_PARENTHESIS);
				State = 204; _localctx.last = binaryExpression(0);
				State = 205; Match(R_PARENTHESIS);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 207; _localctx.funcName = Match(IDENTIFIER);
				State = 208; Match(L_PARENTHESIS);
				State = 209; Match(R_PARENTHESIS);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 18: return binaryExpression_sempred((BinaryExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool binaryExpression_sempred(BinaryExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 7);
		case 1: return Precpred(Context, 6);
		case 2: return Precpred(Context, 5);
		case 3: return Precpred(Context, 4);
		case 4: return Precpred(Context, 3);
		case 5: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x1D', '\xD7', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x3', '\x2', '\x6', '\x2', '.', '\n', '\x2', '\r', 
		'\x2', '\xE', '\x2', '/', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '\x34', 
		'\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x5', '\x5', ';', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x43', 
		'\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x6', '\t', 'M', '\n', '\t', 
		'\r', '\t', '\xE', '\t', 'N', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x5', '\t', 'Z', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\a', '\v', 
		'\x64', '\n', '\v', '\f', '\v', '\xE', '\v', 'g', '\v', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x5', '\f', 'm', '\n', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x5', '\xE', '\x80', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', '\x8C', '\n', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\x90', '\n', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', 
		'\x9B', '\n', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\xA4', 
		'\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\a', '\x14', '\xBB', '\n', '\x14', '\f', 
		'\x14', '\xE', '\x14', '\xBE', '\v', '\x14', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x6', '\x16', 
		'\xC6', '\n', '\x16', '\r', '\x16', '\xE', '\x16', '\xC7', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x5', '\x16', '\xD5', '\n', '\x16', '\x3', '\x16', '\x2', '\x3', '&', 
		'\x17', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', 
		'*', '\x2', '\x3', '\x4', '\x2', '\x12', '\x12', '\x18', '\x18', '\x2', 
		'\xE1', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x4', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x6', '\x35', '\x3', '\x2', '\x2', '\x2', '\b', 
		':', '\x3', '\x2', '\x2', '\x2', '\n', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\f', '\x44', '\x3', '\x2', '\x2', '\x2', '\xE', 'G', '\x3', '\x2', '\x2', 
		'\x2', '\x10', 'Y', '\x3', '\x2', '\x2', '\x2', '\x12', '[', '\x3', '\x2', 
		'\x2', '\x2', '\x14', '\x61', '\x3', '\x2', '\x2', '\x2', '\x16', 'l', 
		'\x3', '\x2', '\x2', '\x2', '\x18', 'n', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'x', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\x8B', '\x3', '\x2', '\x2', '\x2', ' ', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\"', '\x9A', '\x3', '\x2', '\x2', '\x2', '$', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '&', '\xA5', '\x3', '\x2', '\x2', '\x2', '(', 
		'\xBF', '\x3', '\x2', '\x2', '\x2', '*', '\xD4', '\x3', '\x2', '\x2', 
		'\x2', ',', '.', '\x5', '\b', '\x5', '\x2', '-', ',', '\x3', '\x2', '\x2', 
		'\x2', '.', '/', '\x3', '\x2', '\x2', '\x2', '/', '-', '\x3', '\x2', '\x2', 
		'\x2', '/', '\x30', '\x3', '\x2', '\x2', '\x2', '\x30', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x34', '\x5', '\x1E', '\x10', '\x2', '\x32', 
		'\x34', '\x5', ' ', '\x11', '\x2', '\x33', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x32', '\x3', '\x2', '\x2', '\x2', '\x34', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x36', '\a', '\x6', '\x2', '\x2', '\x36', 
		'\x37', '\a', '\a', '\x2', '\x2', '\x37', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x38', ';', '\x5', '\x12', '\n', '\x2', '\x39', ';', '\x5', '\n', '\x6', 
		'\x2', ':', '\x38', '\x3', '\x2', '\x2', '\x2', ':', '\x39', '\x3', '\x2', 
		'\x2', '\x2', ';', '\t', '\x3', '\x2', '\x2', '\x2', '<', '\x43', '\x5', 
		'\x18', '\r', '\x2', '=', '\x43', '\x5', '\x1C', '\xF', '\x2', '>', '\x43', 
		'\x5', '\x1A', '\xE', '\x2', '?', '\x43', '\x5', '\x14', '\v', '\x2', 
		'@', '\x43', '\x5', '\x1E', '\x10', '\x2', '\x41', '\x43', '\x5', '\x16', 
		'\f', '\x2', '\x42', '<', '\x3', '\x2', '\x2', '\x2', '\x42', '=', '\x3', 
		'\x2', '\x2', '\x2', '\x42', '>', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'?', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', '\x2', '\x2', '\x2', 
		'\x42', '\x41', '\x3', '\x2', '\x2', '\x2', '\x43', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x44', '\x45', '\a', '\x19', '\x2', '\x2', '\x45', '\x46', 
		'\x5', '\x6', '\x4', '\x2', '\x46', '\r', '\x3', '\x2', '\x2', '\x2', 
		'G', 'H', '\x5', '\f', '\a', '\x2', 'H', 'I', '\a', '\x5', '\x2', '\x2', 
		'I', '\xF', '\x3', '\x2', '\x2', '\x2', 'J', 'L', '\a', '\x1A', '\x2', 
		'\x2', 'K', 'M', '\x5', '\xE', '\b', '\x2', 'L', 'K', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'N', '\x3', '\x2', '\x2', '\x2', 'N', 'L', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'O', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'P', 'Q', '\x5', '\f', '\a', '\x2', 'Q', 'R', '\a', '\x1B', '\x2', 
		'\x2', 'R', 'Z', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '\x1A', '\x2', 
		'\x2', 'T', 'U', '\x5', '\f', '\a', '\x2', 'U', 'V', '\a', '\x1B', '\x2', 
		'\x2', 'V', 'Z', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', '\x1A', '\x2', 
		'\x2', 'X', 'Z', '\a', '\x1B', '\x2', '\x2', 'Y', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'S', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '\x11', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', '\x10', 
		'\x2', '\x2', '\\', ']', '\a', '\x19', '\x2', '\x2', ']', '^', '\x5', 
		'\x10', '\t', '\x2', '^', '_', '\x5', '\x6', '\x4', '\x2', '_', '`', '\x5', 
		'\n', '\x6', '\x2', '`', '\x13', '\x3', '\x2', '\x2', '\x2', '\x61', '\x65', 
		'\a', '\x1C', '\x2', '\x2', '\x62', '\x64', '\x5', '\n', '\x6', '\x2', 
		'\x63', '\x62', '\x3', '\x2', '\x2', '\x2', '\x64', 'g', '\x3', '\x2', 
		'\x2', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', 
		'\x3', '\x2', '\x2', '\x2', '\x66', 'h', '\x3', '\x2', '\x2', '\x2', 'g', 
		'\x65', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\a', '\x1D', '\x2', '\x2', 
		'i', '\x15', '\x3', '\x2', '\x2', '\x2', 'j', 'm', '\x5', ' ', '\x11', 
		'\x2', 'k', 'm', '\x5', '&', '\x14', '\x2', 'l', 'j', '\x3', '\x2', '\x2', 
		'\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 'm', '\x17', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'o', '\a', '\xF', '\x2', '\x2', 'o', 'p', '\a', '\x1A', 
		'\x2', '\x2', 'p', 'q', '\x5', '\x4', '\x3', '\x2', 'q', 'r', '\a', '\x5', 
		'\x2', '\x2', 'r', 's', '\x5', '&', '\x14', '\x2', 's', 't', '\a', '\x5', 
		'\x2', '\x2', 't', 'u', '\x5', ' ', '\x11', '\x2', 'u', 'v', '\a', '\x1B', 
		'\x2', '\x2', 'v', 'w', '\x5', '\n', '\x6', '\x2', 'w', '\x19', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'y', '\a', '\f', '\x2', '\x2', 'y', 'z', '\a', 
		'\x1A', '\x2', '\x2', 'z', '{', '\x5', '&', '\x14', '\x2', '{', '|', '\a', 
		'\x1B', '\x2', '\x2', '|', '\x7F', '\x5', '\n', '\x6', '\x2', '}', '~', 
		'\a', '\r', '\x2', '\x2', '~', '\x80', '\x5', '\n', '\x6', '\x2', '\x7F', 
		'}', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\a', 
		'\xE', '\x2', '\x2', '\x82', '\x83', '\a', '\x1A', '\x2', '\x2', '\x83', 
		'\x84', '\x5', '&', '\x14', '\x2', '\x84', '\x85', '\a', '\x1B', '\x2', 
		'\x2', '\x85', '\x86', '\x5', '\n', '\x6', '\x2', '\x86', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x88', '\a', '\v', '\x2', '\x2', '\x88', 
		'\x8C', '\x5', '\f', '\a', '\x2', '\x89', '\x8A', '\a', '\v', '\x2', '\x2', 
		'\x8A', '\x8C', '\x5', ' ', '\x11', '\x2', '\x8B', '\x87', '\x3', '\x2', 
		'\x2', '\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x1F', 
		'\x3', '\x2', '\x2', '\x2', '\x8D', '\x8F', '\a', '\x19', '\x2', '\x2', 
		'\x8E', '\x90', '\x5', '\x6', '\x4', '\x2', '\x8F', '\x8E', '\x3', '\x2', 
		'\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', 
		'\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\a', '\x11', '\x2', '\x2', 
		'\x92', '\x93', '\x5', '&', '\x14', '\x2', '\x93', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x94', '\x9B', '\a', '\t', '\x2', '\x2', '\x95', '\x9B', 
		'\a', '\n', '\x2', '\x2', '\x96', '\x9B', '\a', '\b', '\x2', '\x2', '\x97', 
		'\x9B', '\x5', '*', '\x16', '\x2', '\x98', '\x9B', '\a', '\x19', '\x2', 
		'\x2', '\x99', '\x9B', '\a', '\x3', '\x2', '\x2', '\x9A', '\x94', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x95', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\x9B', '#', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', '\x1A', '\x2', '\x2', '\x9D', '\x9E', '\x5', '&', '\x14', 
		'\x2', '\x9E', '\x9F', '\a', '\x1B', '\x2', '\x2', '\x9F', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA1', '\t', '\x2', '\x2', '\x2', '\xA1', 
		'\xA4', '\x5', '$', '\x13', '\x2', '\xA2', '\xA4', '\x5', '\"', '\x12', 
		'\x2', '\xA3', '\x9C', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xA3', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', 
		'%', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\b', '\x14', '\x1', 
		'\x2', '\xA6', '\xA7', '\x5', '$', '\x13', '\x2', '\xA7', '\xBC', '\x3', 
		'\x2', '\x2', '\x2', '\xA8', '\xA9', '\f', '\t', '\x2', '\x2', '\xA9', 
		'\xAA', '\a', '\x14', '\x2', '\x2', '\xAA', '\xBB', '\x5', '&', '\x14', 
		'\n', '\xAB', '\xAC', '\f', '\b', '\x2', '\x2', '\xAC', '\xAD', '\a', 
		'\x13', '\x2', '\x2', '\xAD', '\xBB', '\x5', '&', '\x14', '\t', '\xAE', 
		'\xAF', '\f', '\a', '\x2', '\x2', '\xAF', '\xB0', '\a', '\x12', '\x2', 
		'\x2', '\xB0', '\xBB', '\x5', '&', '\x14', '\b', '\xB1', '\xB2', '\f', 
		'\x6', '\x2', '\x2', '\xB2', '\xB3', '\a', '\x15', '\x2', '\x2', '\xB3', 
		'\xBB', '\x5', '&', '\x14', '\a', '\xB4', '\xB5', '\f', '\x5', '\x2', 
		'\x2', '\xB5', '\xB6', '\a', '\x16', '\x2', '\x2', '\xB6', '\xBB', '\x5', 
		'&', '\x14', '\x6', '\xB7', '\xB8', '\f', '\x4', '\x2', '\x2', '\xB8', 
		'\xB9', '\a', '\x17', '\x2', '\x2', '\xB9', '\xBB', '\x5', '&', '\x14', 
		'\x5', '\xBA', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\xBA', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xBA', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xB4', '\x3', '\x2', '\x2', 
		'\x2', '\xBA', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\xBD', '\x3', '\x2', '\x2', '\x2', '\xBD', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\x5', 
		'&', '\x14', '\x2', '\xC0', '\xC1', '\a', '\x5', '\x2', '\x2', '\xC1', 
		')', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC3', '\a', '\x19', '\x2', 
		'\x2', '\xC3', '\xC5', '\a', '\x1A', '\x2', '\x2', '\xC4', '\xC6', '\x5', 
		'(', '\x15', '\x2', '\xC5', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC6', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC5', '\x3', '\x2', '\x2', 
		'\x2', '\xC7', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC9', '\x3', 
		'\x2', '\x2', '\x2', '\xC9', '\xCA', '\x5', '&', '\x14', '\x2', '\xCA', 
		'\xCB', '\a', '\x1B', '\x2', '\x2', '\xCB', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\xCC', '\xCD', '\a', '\x19', '\x2', '\x2', '\xCD', '\xCE', '\a', 
		'\x1A', '\x2', '\x2', '\xCE', '\xCF', '\x5', '&', '\x14', '\x2', '\xCF', 
		'\xD0', '\a', '\x1B', '\x2', '\x2', '\xD0', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\xD1', '\xD2', '\a', '\x19', '\x2', '\x2', '\xD2', '\xD3', '\a', 
		'\x1A', '\x2', '\x2', '\xD3', '\xD5', '\a', '\x1B', '\x2', '\x2', '\xD4', 
		'\xC2', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xCC', '\x3', '\x2', '\x2', 
		'\x2', '\xD4', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD5', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '/', '\x33', ':', '\x42', 'N', 'Y', '\x65', 
		'l', '\x7F', '\x8B', '\x8F', '\x9A', '\xA3', '\xBA', '\xBC', '\xC7', '\xD4',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace InterpreterLib
