//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace InterpreterLib {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GLangLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		STRING=1, WHITESPACE=2, COMMA=3, TYPE_DELIMETER=4, TYPE_NAME=5, BOOLEAN=6, 
		INTEGER=7, DECL_VARIABLE=8, IF=9, ELSE=10, WHILE=11, FOR=12, FUNCTION=13, 
		ASSIGNMENT_OPERATOR=14, ADDITIVE_OP=15, MULTIPLICATIVE_OP=16, CARAT=17, 
		LOW_PRIORITY_OP=18, COMPARE_OP=19, LOGICAL_OP=20, BANG=21, IDENTIFIER=22, 
		L_PARENTHESIS=23, R_PARENTHESIS=24, L_BRACE=25, R_BRACE=26, UNKNOWN_CHAR=27;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"DIGIT", "TRUE", "FALSE", "CHARACTER", "VAR", "VAL", "INT", "BOOL", "STRING_TYPE", 
		"EQUALITY_OPERATOR", "GREATER", "LESSER", "GREATER_STRICT", "LESSER_STRICT", 
		"MOD_OPERATOR", "STRING", "WHITESPACE", "COMMA", "TYPE_DELIMETER", "TYPE_NAME", 
		"BOOLEAN", "INTEGER", "DECL_VARIABLE", "IF", "ELSE", "WHILE", "FOR", "FUNCTION", 
		"ASSIGNMENT_OPERATOR", "ADDITIVE_OP", "MULTIPLICATIVE_OP", "CARAT", "LOW_PRIORITY_OP", 
		"COMPARE_OP", "LOGICAL_OP", "BANG", "IDENTIFIER", "L_PARENTHESIS", "R_PARENTHESIS", 
		"L_BRACE", "R_BRACE", "UNKNOWN_CHAR"
	};


	public GLangLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GLangLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, "','", "':'", null, null, null, null, "'if'", "'else'", 
		"'while'", "'for'", "'function'", null, null, null, "'^'", null, null, 
		null, "'!'", null, "'('", "')'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "STRING", "WHITESPACE", "COMMA", "TYPE_DELIMETER", "TYPE_NAME", 
		"BOOLEAN", "INTEGER", "DECL_VARIABLE", "IF", "ELSE", "WHILE", "FOR", "FUNCTION", 
		"ASSIGNMENT_OPERATOR", "ADDITIVE_OP", "MULTIPLICATIVE_OP", "CARAT", "LOW_PRIORITY_OP", 
		"COMPARE_OP", "LOGICAL_OP", "BANG", "IDENTIFIER", "L_PARENTHESIS", "R_PARENTHESIS", 
		"L_BRACE", "R_BRACE", "UNKNOWN_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GLangLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1D', '\x106', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x4', ')', 
		'\t', ')', '\x4', '*', '\t', '*', '\x4', '+', '\t', '+', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\a', '\x11', '\x90', '\n', '\x11', '\f', 
		'\x11', '\xE', '\x11', '\x93', '\v', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x6', '\x12', '\x98', '\n', '\x12', '\r', '\x12', '\xE', 
		'\x12', '\x99', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x5', '\x15', '\xA5', '\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\x5', 
		'\x16', '\xA9', '\n', '\x16', '\x3', '\x17', '\x6', '\x17', '\xAC', '\n', 
		'\x17', '\r', '\x17', '\xE', '\x17', '\xAD', '\x3', '\x18', '\x3', '\x18', 
		'\x5', '\x18', '\xB2', '\n', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x5', '\x1E', '\xD8', 
		'\n', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', 
		'!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', 
		'#', '\x3', '#', '\x3', '#', '\x5', '#', '\xE7', '\n', '#', '\x3', '$', 
		'\x3', '$', '\x3', '$', '\x3', '$', '\x5', '$', '\xED', '\n', '$', '\x3', 
		'%', '\x3', '%', '\x3', '&', '\x3', '&', '\x5', '&', '\xF3', '\n', '&', 
		'\x3', '&', '\x3', '&', '\x3', '&', '\a', '&', '\xF8', '\n', '&', '\f', 
		'&', '\xE', '&', '\xFB', '\v', '&', '\x3', '\'', '\x3', '\'', '\x3', '(', 
		'\x3', '(', '\x3', ')', '\x3', ')', '\x3', '*', '\x3', '*', '\x3', '+', 
		'\x3', '+', '\x3', '\x91', '\x2', ',', '\x3', '\x2', '\x5', '\x2', '\a', 
		'\x2', '\t', '\x2', '\v', '\x2', '\r', '\x2', '\xF', '\x2', '\x11', '\x2', 
		'\x13', '\x2', '\x15', '\x2', '\x17', '\x2', '\x19', '\x2', '\x1B', '\x2', 
		'\x1D', '\x2', '\x1F', '\x2', '!', '\x3', '#', '\x4', '%', '\x5', '\'', 
		'\x6', ')', '\a', '+', '\b', '-', '\t', '/', '\n', '\x31', '\v', '\x33', 
		'\f', '\x35', '\r', '\x37', '\xE', '\x39', '\xF', ';', '\x10', '=', '\x11', 
		'?', '\x12', '\x41', '\x13', '\x43', '\x14', '\x45', '\x15', 'G', '\x16', 
		'I', '\x17', 'K', '\x18', 'M', '\x19', 'O', '\x1A', 'Q', '\x1B', 'S', 
		'\x1C', 'U', '\x1D', '\x3', '\x2', '\b', '\x4', '\x2', 'V', 'V', 'v', 
		'v', '\x4', '\x2', 'H', 'H', 'h', 'h', '\x4', '\x2', '\x43', '\\', '\x63', 
		'|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', '\x2', 
		'-', '-', '/', '/', '\x4', '\x2', ',', ',', '\x31', '\x31', '\x2', '\x10A', 
		'\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 'G', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', '\x2', '\x2', '\x2', 'K', 
		'\x3', '\x2', '\x2', '\x2', '\x2', 'M', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'O', '\x3', '\x2', '\x2', '\x2', '\x2', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'S', '\x3', '\x2', '\x2', '\x2', '\x2', 'U', '\x3', '\x2', '\x2', 
		'\x2', '\x3', 'W', '\x3', '\x2', '\x2', '\x2', '\x5', 'Y', '\x3', '\x2', 
		'\x2', '\x2', '\a', '^', '\x3', '\x2', '\x2', '\x2', '\t', '\x64', '\x3', 
		'\x2', '\x2', '\x2', '\v', '\x66', '\x3', '\x2', '\x2', '\x2', '\r', 'j', 
		'\x3', '\x2', '\x2', '\x2', '\xF', 'n', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'r', '\x3', '\x2', '\x2', '\x2', '\x13', 'w', '\x3', '\x2', '\x2', '\x2', 
		'\x15', '|', '\x3', '\x2', '\x2', '\x2', '\x17', '\x7F', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\x82', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\x87', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\x89', '\x3', '\x2', '\x2', '\x2', '!', '\x8D', '\x3', '\x2', 
		'\x2', '\x2', '#', '\x97', '\x3', '\x2', '\x2', '\x2', '%', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\'', '\x9F', '\x3', '\x2', '\x2', '\x2', ')', '\xA4', 
		'\x3', '\x2', '\x2', '\x2', '+', '\xA8', '\x3', '\x2', '\x2', '\x2', '-', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '/', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\xB3', '\x3', '\x2', '\x2', '\x2', '\x33', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\xBB', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\xC1', '\x3', '\x2', '\x2', '\x2', '\x39', '\xC5', '\x3', '\x2', '\x2', 
		'\x2', ';', '\xD7', '\x3', '\x2', '\x2', '\x2', '=', '\xD9', '\x3', '\x2', 
		'\x2', '\x2', '?', '\xDB', '\x3', '\x2', '\x2', '\x2', '\x41', '\xDD', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\xDF', '\x3', '\x2', '\x2', '\x2', 
		'\x45', '\xE6', '\x3', '\x2', '\x2', '\x2', 'G', '\xEC', '\x3', '\x2', 
		'\x2', '\x2', 'I', '\xEE', '\x3', '\x2', '\x2', '\x2', 'K', '\xF2', '\x3', 
		'\x2', '\x2', '\x2', 'M', '\xFC', '\x3', '\x2', '\x2', '\x2', 'O', '\xFE', 
		'\x3', '\x2', '\x2', '\x2', 'Q', '\x100', '\x3', '\x2', '\x2', '\x2', 
		'S', '\x102', '\x3', '\x2', '\x2', '\x2', 'U', '\x104', '\x3', '\x2', 
		'\x2', '\x2', 'W', 'X', '\x4', '\x32', ';', '\x2', 'X', '\x4', '\x3', 
		'\x2', '\x2', '\x2', 'Y', 'Z', '\t', '\x2', '\x2', '\x2', 'Z', '[', '\a', 
		't', '\x2', '\x2', '[', '\\', '\a', 'w', '\x2', '\x2', '\\', ']', '\a', 
		'g', '\x2', '\x2', ']', '\x6', '\x3', '\x2', '\x2', '\x2', '^', '_', '\t', 
		'\x3', '\x2', '\x2', '_', '`', '\a', '\x63', '\x2', '\x2', '`', '\x61', 
		'\a', 'n', '\x2', '\x2', '\x61', '\x62', '\a', 'u', '\x2', '\x2', '\x62', 
		'\x63', '\a', 'g', '\x2', '\x2', '\x63', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\x65', '\t', '\x4', '\x2', '\x2', '\x65', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x66', 'g', '\a', 'x', '\x2', '\x2', 'g', 'h', '\a', '\x63', 
		'\x2', '\x2', 'h', 'i', '\a', 't', '\x2', '\x2', 'i', '\f', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'k', '\a', 'x', '\x2', '\x2', 'k', 'l', '\a', '\x63', 
		'\x2', '\x2', 'l', 'm', '\a', 'n', '\x2', '\x2', 'm', '\xE', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'o', '\a', 'k', '\x2', '\x2', 'o', 'p', '\a', 'p', 
		'\x2', '\x2', 'p', 'q', '\a', 'v', '\x2', '\x2', 'q', '\x10', '\x3', '\x2', 
		'\x2', '\x2', 'r', 's', '\a', '\x64', '\x2', '\x2', 's', 't', '\a', 'q', 
		'\x2', '\x2', 't', 'u', '\a', 'q', '\x2', '\x2', 'u', 'v', '\a', 'n', 
		'\x2', '\x2', 'v', '\x12', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', 
		'\x64', '\x2', '\x2', 'x', 'y', '\a', 'q', '\x2', '\x2', 'y', 'z', '\a', 
		'q', '\x2', '\x2', 'z', '{', '\a', 'n', '\x2', '\x2', '{', '\x14', '\x3', 
		'\x2', '\x2', '\x2', '|', '}', '\a', '?', '\x2', '\x2', '}', '~', '\a', 
		'?', '\x2', '\x2', '~', '\x16', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', 
		'\a', '@', '\x2', '\x2', '\x80', '\x81', '\a', '?', '\x2', '\x2', '\x81', 
		'\x18', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\a', '>', '\x2', 
		'\x2', '\x83', '\x84', '\a', '?', '\x2', '\x2', '\x84', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x86', '\a', '@', '\x2', '\x2', '\x86', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\a', '>', '\x2', 
		'\x2', '\x88', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\a', 
		'o', '\x2', '\x2', '\x8A', '\x8B', '\a', 'q', '\x2', '\x2', '\x8B', '\x8C', 
		'\a', '\x66', '\x2', '\x2', '\x8C', ' ', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x91', '\a', '$', '\x2', '\x2', '\x8E', '\x90', '\v', '\x2', '\x2', '\x2', 
		'\x8F', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x92', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', 
		'\x3', '\x2', '\x2', '\x2', '\x92', '\x94', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x91', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\a', '$', 
		'\x2', '\x2', '\x95', '\"', '\x3', '\x2', '\x2', '\x2', '\x96', '\x98', 
		'\t', '\x5', '\x2', '\x2', '\x97', '\x96', '\x3', '\x2', '\x2', '\x2', 
		'\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x99', '\x97', '\x3', '\x2', 
		'\x2', '\x2', '\x99', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', 
		'\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\b', '\x12', '\x2', '\x2', 
		'\x9C', '$', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\a', '.', '\x2', 
		'\x2', '\x9E', '&', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		'<', '\x2', '\x2', '\xA0', '(', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA5', 
		'\x5', '\xF', '\b', '\x2', '\xA2', '\xA5', '\x5', '\x11', '\t', '\x2', 
		'\xA3', '\xA5', '\x5', '\x13', '\n', '\x2', '\xA4', '\xA1', '\x3', '\x2', 
		'\x2', '\x2', '\xA4', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA5', '*', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA9', '\x5', '\x5', '\x3', '\x2', '\xA7', '\xA9', '\x5', '\a', '\x4', 
		'\x2', '\xA8', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', '\xA9', ',', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xAC', '\x5', '\x3', '\x2', '\x2', '\xAB', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB2', '\x5', '\r', '\a', '\x2', 
		'\xB0', '\xB2', '\x5', '\v', '\x6', '\x2', '\xB1', '\xAF', '\x3', '\x2', 
		'\x2', '\x2', '\xB1', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB2', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\a', 'k', '\x2', '\x2', '\xB4', 
		'\xB5', '\a', 'h', '\x2', '\x2', '\xB5', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xB7', '\a', 'g', '\x2', '\x2', '\xB7', '\xB8', '\a', 
		'n', '\x2', '\x2', '\xB8', '\xB9', '\a', 'u', '\x2', '\x2', '\xB9', '\xBA', 
		'\a', 'g', '\x2', '\x2', '\xBA', '\x34', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xBC', '\a', 'y', '\x2', '\x2', '\xBC', '\xBD', '\a', 'j', '\x2', '\x2', 
		'\xBD', '\xBE', '\a', 'k', '\x2', '\x2', '\xBE', '\xBF', '\a', 'n', '\x2', 
		'\x2', '\xBF', '\xC0', '\a', 'g', '\x2', '\x2', '\xC0', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\xC1', '\xC2', '\a', 'h', '\x2', '\x2', '\xC2', 
		'\xC3', '\a', 'q', '\x2', '\x2', '\xC3', '\xC4', '\a', 't', '\x2', '\x2', 
		'\xC4', '\x38', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', '\a', 'h', 
		'\x2', '\x2', '\xC6', '\xC7', '\a', 'w', '\x2', '\x2', '\xC7', '\xC8', 
		'\a', 'p', '\x2', '\x2', '\xC8', '\xC9', '\a', '\x65', '\x2', '\x2', '\xC9', 
		'\xCA', '\a', 'v', '\x2', '\x2', '\xCA', '\xCB', '\a', 'k', '\x2', '\x2', 
		'\xCB', '\xCC', '\a', 'q', '\x2', '\x2', '\xCC', '\xCD', '\a', 'p', '\x2', 
		'\x2', '\xCD', ':', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCF', '\a', 
		'-', '\x2', '\x2', '\xCF', '\xD8', '\a', '?', '\x2', '\x2', '\xD0', '\xD1', 
		'\a', '/', '\x2', '\x2', '\xD1', '\xD8', '\a', '?', '\x2', '\x2', '\xD2', 
		'\xD3', '\a', ',', '\x2', '\x2', '\xD3', '\xD8', '\a', '?', '\x2', '\x2', 
		'\xD4', '\xD5', '\a', '\x31', '\x2', '\x2', '\xD5', '\xD8', '\a', '?', 
		'\x2', '\x2', '\xD6', '\xD8', '\a', '?', '\x2', '\x2', '\xD7', '\xCE', 
		'\x3', '\x2', '\x2', '\x2', '\xD7', '\xD0', '\x3', '\x2', '\x2', '\x2', 
		'\xD7', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD4', '\x3', '\x2', 
		'\x2', '\x2', '\xD7', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD8', '<', 
		'\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\t', '\x6', '\x2', '\x2', 
		'\xDA', '>', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDC', '\t', '\a', '\x2', 
		'\x2', '\xDC', '@', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\a', 
		'`', '\x2', '\x2', '\xDE', '\x42', '\x3', '\x2', '\x2', '\x2', '\xDF', 
		'\xE0', '\x5', '\x1F', '\x10', '\x2', '\xE0', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\xE1', '\xE7', '\x5', '\x15', '\v', '\x2', '\xE2', '\xE7', '\x5', 
		'\x17', '\f', '\x2', '\xE3', '\xE7', '\x5', '\x19', '\r', '\x2', '\xE4', 
		'\xE7', '\x5', '\x1B', '\xE', '\x2', '\xE5', '\xE7', '\x5', '\x1D', '\xF', 
		'\x2', '\xE6', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE2', '\x3', 
		'\x2', '\x2', '\x2', '\xE6', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE6', 
		'\xE4', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE5', '\x3', '\x2', '\x2', 
		'\x2', '\xE7', '\x46', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xE9', '\a', 
		'(', '\x2', '\x2', '\xE9', '\xED', '\a', '(', '\x2', '\x2', '\xEA', '\xEB', 
		'\a', '~', '\x2', '\x2', '\xEB', '\xED', '\a', '~', '\x2', '\x2', '\xEC', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '\xED', 'H', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xEF', '\a', 
		'#', '\x2', '\x2', '\xEF', 'J', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xF3', 
		'\x5', '\t', '\x5', '\x2', '\xF1', '\xF3', '\a', '\x61', '\x2', '\x2', 
		'\xF2', '\xF0', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF1', '\x3', '\x2', 
		'\x2', '\x2', '\xF3', '\xF9', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF8', 
		'\x5', '\t', '\x5', '\x2', '\xF5', '\xF8', '\x5', '\x3', '\x2', '\x2', 
		'\xF6', '\xF8', '\a', '\x61', '\x2', '\x2', '\xF7', '\xF4', '\x3', '\x2', 
		'\x2', '\x2', '\xF7', '\xF5', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF6', 
		'\x3', '\x2', '\x2', '\x2', '\xF8', '\xFB', '\x3', '\x2', '\x2', '\x2', 
		'\xF9', '\xF7', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xFA', '\x3', '\x2', 
		'\x2', '\x2', '\xFA', 'L', '\x3', '\x2', '\x2', '\x2', '\xFB', '\xF9', 
		'\x3', '\x2', '\x2', '\x2', '\xFC', '\xFD', '\a', '*', '\x2', '\x2', '\xFD', 
		'N', '\x3', '\x2', '\x2', '\x2', '\xFE', '\xFF', '\a', '+', '\x2', '\x2', 
		'\xFF', 'P', '\x3', '\x2', '\x2', '\x2', '\x100', '\x101', '\a', '}', 
		'\x2', '\x2', '\x101', 'R', '\x3', '\x2', '\x2', '\x2', '\x102', '\x103', 
		'\a', '\x7F', '\x2', '\x2', '\x103', 'T', '\x3', '\x2', '\x2', '\x2', 
		'\x104', '\x105', '\v', '\x2', '\x2', '\x2', '\x105', 'V', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '\x2', '\x91', '\x99', '\xA4', '\xA8', '\xAD', '\xB1', 
		'\xD7', '\xE6', '\xEC', '\xF2', '\xF7', '\xF9', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace InterpreterLib
