//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace InterpreterLib {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GLangLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		STRING=1, WHITESPACE=2, COMMA=3, TYPE_DELIMETER=4, TYPE_NAME=5, BOOLEAN=6, 
		INTEGER=7, DECL_VARIABLE=8, IF=9, ELSE=10, WHILE=11, FOR=12, FUNCTION=13, 
		ASSIGNMENT_OPERATOR=14, ADDITIVE_OP=15, MULTIPLICATIVE_OP=16, CARAT=17, 
		LOW_PRIORITY_OP=18, COMPARE_OP=19, LOGICAL_OP=20, BANG=21, IDENTIFIER=22, 
		L_PARENTHESIS=23, R_PARENTHESIS=24, L_BRACE=25, R_BRACE=26;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"DIGIT", "TRUE", "FALSE", "CHARACTER", "VAR", "VAL", "INT", "BOOL", "STRING_TYPE", 
		"EQUALITY_OPERATOR", "GREATER", "LESSER", "GREATER_STRICT", "LESSER_STRICT", 
		"MOD_OPERATOR", "STRING", "WHITESPACE", "COMMA", "TYPE_DELIMETER", "TYPE_NAME", 
		"BOOLEAN", "INTEGER", "DECL_VARIABLE", "IF", "ELSE", "WHILE", "FOR", "FUNCTION", 
		"ASSIGNMENT_OPERATOR", "ADDITIVE_OP", "MULTIPLICATIVE_OP", "CARAT", "LOW_PRIORITY_OP", 
		"COMPARE_OP", "LOGICAL_OP", "BANG", "IDENTIFIER", "L_PARENTHESIS", "R_PARENTHESIS", 
		"L_BRACE", "R_BRACE"
	};


	public GLangLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GLangLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, "','", "':'", null, null, null, null, "'if'", "'else'", 
		"'while'", "'for'", "'function'", null, null, null, "'^'", null, null, 
		null, "'!'", null, "'('", "')'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "STRING", "WHITESPACE", "COMMA", "TYPE_DELIMETER", "TYPE_NAME", 
		"BOOLEAN", "INTEGER", "DECL_VARIABLE", "IF", "ELSE", "WHILE", "FOR", "FUNCTION", 
		"ASSIGNMENT_OPERATOR", "ADDITIVE_OP", "MULTIPLICATIVE_OP", "CARAT", "LOW_PRIORITY_OP", 
		"COMPARE_OP", "LOGICAL_OP", "BANG", "IDENTIFIER", "L_PARENTHESIS", "R_PARENTHESIS", 
		"L_BRACE", "R_BRACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GLangLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1C', '\x102', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x4', ')', 
		'\t', ')', '\x4', '*', '\t', '*', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\a', '\x11', '\x8E', '\n', '\x11', '\f', '\x11', '\xE', '\x11', '\x91', 
		'\v', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x6', '\x12', 
		'\x96', '\n', '\x12', '\r', '\x12', '\xE', '\x12', '\x97', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x5', '\x15', '\xA3', '\n', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x5', '\x16', '\xA7', '\n', '\x16', 
		'\x3', '\x17', '\x6', '\x17', '\xAA', '\n', '\x17', '\r', '\x17', '\xE', 
		'\x17', '\xAB', '\x3', '\x18', '\x3', '\x18', '\x5', '\x18', '\xB0', '\n', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x5', '\x1E', '\xD6', '\n', '\x1E', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x3', '!', '\x3', 
		'\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', 
		'#', '\x5', '#', '\xE5', '\n', '#', '\x3', '$', '\x3', '$', '\x3', '$', 
		'\x3', '$', '\x5', '$', '\xEB', '\n', '$', '\x3', '%', '\x3', '%', '\x3', 
		'&', '\x3', '&', '\x5', '&', '\xF1', '\n', '&', '\x3', '&', '\x3', '&', 
		'\x3', '&', '\a', '&', '\xF6', '\n', '&', '\f', '&', '\xE', '&', '\xF9', 
		'\v', '&', '\x3', '\'', '\x3', '\'', '\x3', '(', '\x3', '(', '\x3', ')', 
		'\x3', ')', '\x3', '*', '\x3', '*', '\x3', '\x8F', '\x2', '+', '\x3', 
		'\x2', '\x5', '\x2', '\a', '\x2', '\t', '\x2', '\v', '\x2', '\r', '\x2', 
		'\xF', '\x2', '\x11', '\x2', '\x13', '\x2', '\x15', '\x2', '\x17', '\x2', 
		'\x19', '\x2', '\x1B', '\x2', '\x1D', '\x2', '\x1F', '\x2', '!', '\x3', 
		'#', '\x4', '%', '\x5', '\'', '\x6', ')', '\a', '+', '\b', '-', '\t', 
		'/', '\n', '\x31', '\v', '\x33', '\f', '\x35', '\r', '\x37', '\xE', '\x39', 
		'\xF', ';', '\x10', '=', '\x11', '?', '\x12', '\x41', '\x13', '\x43', 
		'\x14', '\x45', '\x15', 'G', '\x16', 'I', '\x17', 'K', '\x18', 'M', '\x19', 
		'O', '\x1A', 'Q', '\x1B', 'S', '\x1C', '\x3', '\x2', '\b', '\x4', '\x2', 
		'V', 'V', 'v', 'v', '\x4', '\x2', 'H', 'H', 'h', 'h', '\x4', '\x2', '\x43', 
		'\\', '\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x4', '\x2', '-', '-', '/', '/', '\x4', '\x2', ',', ',', '\x31', '\x31', 
		'\x2', '\x106', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x2', 'M', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'O', '\x3', '\x2', '\x2', '\x2', '\x2', 'Q', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'S', '\x3', '\x2', '\x2', '\x2', '\x3', 'U', '\x3', 
		'\x2', '\x2', '\x2', '\x5', 'W', '\x3', '\x2', '\x2', '\x2', '\a', '\\', 
		'\x3', '\x2', '\x2', '\x2', '\t', '\x62', '\x3', '\x2', '\x2', '\x2', 
		'\v', '\x64', '\x3', '\x2', '\x2', '\x2', '\r', 'h', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'l', '\x3', '\x2', '\x2', '\x2', '\x11', 'p', '\x3', '\x2', 
		'\x2', '\x2', '\x13', 'u', '\x3', '\x2', '\x2', '\x2', '\x15', 'z', '\x3', 
		'\x2', '\x2', '\x2', '\x17', '}', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x80', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x85', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '!', '\x8B', '\x3', '\x2', '\x2', '\x2', '#', '\x95', 
		'\x3', '\x2', '\x2', '\x2', '%', '\x9B', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', ')', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '+', '\xA6', '\x3', '\x2', '\x2', '\x2', '-', '\xA9', '\x3', '\x2', 
		'\x2', '\x2', '/', '\xAF', '\x3', '\x2', '\x2', '\x2', '\x31', '\xB1', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\xB4', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\xB9', '\x3', '\x2', '\x2', '\x2', '\x37', '\xBF', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\xC3', '\x3', '\x2', '\x2', '\x2', ';', '\xD5', 
		'\x3', '\x2', '\x2', '\x2', '=', '\xD7', '\x3', '\x2', '\x2', '\x2', '?', 
		'\xD9', '\x3', '\x2', '\x2', '\x2', '\x41', '\xDB', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\xDD', '\x3', '\x2', '\x2', '\x2', '\x45', '\xE4', '\x3', 
		'\x2', '\x2', '\x2', 'G', '\xEA', '\x3', '\x2', '\x2', '\x2', 'I', '\xEC', 
		'\x3', '\x2', '\x2', '\x2', 'K', '\xF0', '\x3', '\x2', '\x2', '\x2', 'M', 
		'\xFA', '\x3', '\x2', '\x2', '\x2', 'O', '\xFC', '\x3', '\x2', '\x2', 
		'\x2', 'Q', '\xFE', '\x3', '\x2', '\x2', '\x2', 'S', '\x100', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'V', '\x4', '\x32', ';', '\x2', 'V', '\x4', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'X', '\t', '\x2', '\x2', '\x2', 'X', 'Y', '\a', 
		't', '\x2', '\x2', 'Y', 'Z', '\a', 'w', '\x2', '\x2', 'Z', '[', '\a', 
		'g', '\x2', '\x2', '[', '\x6', '\x3', '\x2', '\x2', '\x2', '\\', ']', 
		'\t', '\x3', '\x2', '\x2', ']', '^', '\a', '\x63', '\x2', '\x2', '^', 
		'_', '\a', 'n', '\x2', '\x2', '_', '`', '\a', 'u', '\x2', '\x2', '`', 
		'\x61', '\a', 'g', '\x2', '\x2', '\x61', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x62', '\x63', '\t', '\x4', '\x2', '\x2', '\x63', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x65', '\a', 'x', '\x2', '\x2', '\x65', '\x66', 
		'\a', '\x63', '\x2', '\x2', '\x66', 'g', '\a', 't', '\x2', '\x2', 'g', 
		'\f', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\a', 'x', '\x2', '\x2', 'i', 
		'j', '\a', '\x63', '\x2', '\x2', 'j', 'k', '\a', 'n', '\x2', '\x2', 'k', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', 'k', '\x2', '\x2', 
		'm', 'n', '\a', 'p', '\x2', '\x2', 'n', 'o', '\a', 'v', '\x2', '\x2', 
		'o', '\x10', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '\x64', '\x2', 
		'\x2', 'q', 'r', '\a', 'q', '\x2', '\x2', 'r', 's', '\a', 'q', '\x2', 
		'\x2', 's', 't', '\a', 'n', '\x2', '\x2', 't', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'v', '\a', '\x64', '\x2', '\x2', 'v', 'w', '\a', 'q', '\x2', 
		'\x2', 'w', 'x', '\a', 'q', '\x2', '\x2', 'x', 'y', '\a', 'n', '\x2', 
		'\x2', 'y', '\x14', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '?', '\x2', 
		'\x2', '{', '|', '\a', '?', '\x2', '\x2', '|', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\a', '@', '\x2', '\x2', '~', '\x7F', '\a', '?', '\x2', 
		'\x2', '\x7F', '\x18', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\a', 
		'>', '\x2', '\x2', '\x81', '\x82', '\a', '?', '\x2', '\x2', '\x82', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\a', '@', '\x2', '\x2', '\x84', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\a', '>', '\x2', 
		'\x2', '\x86', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\a', 
		'o', '\x2', '\x2', '\x88', '\x89', '\a', 'q', '\x2', '\x2', '\x89', '\x8A', 
		'\a', '\x66', '\x2', '\x2', '\x8A', ' ', '\x3', '\x2', '\x2', '\x2', '\x8B', 
		'\x8F', '\a', '$', '\x2', '\x2', '\x8C', '\x8E', '\v', '\x2', '\x2', '\x2', 
		'\x8D', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x8D', 
		'\x3', '\x2', '\x2', '\x2', '\x90', '\x92', '\x3', '\x2', '\x2', '\x2', 
		'\x91', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', '$', 
		'\x2', '\x2', '\x93', '\"', '\x3', '\x2', '\x2', '\x2', '\x94', '\x96', 
		'\t', '\x5', '\x2', '\x2', '\x95', '\x94', '\x3', '\x2', '\x2', '\x2', 
		'\x96', '\x97', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', '\x2', 
		'\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\b', '\x12', '\x2', '\x2', 
		'\x9A', '$', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', '.', '\x2', 
		'\x2', '\x9C', '&', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\a', 
		'<', '\x2', '\x2', '\x9E', '(', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA3', 
		'\x5', '\xF', '\b', '\x2', '\xA0', '\xA3', '\x5', '\x11', '\t', '\x2', 
		'\xA1', '\xA3', '\x5', '\x13', '\n', '\x2', '\xA2', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA1', 
		'\x3', '\x2', '\x2', '\x2', '\xA3', '*', '\x3', '\x2', '\x2', '\x2', '\xA4', 
		'\xA7', '\x5', '\x5', '\x3', '\x2', '\xA5', '\xA7', '\x5', '\a', '\x4', 
		'\x2', '\xA6', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA5', '\x3', 
		'\x2', '\x2', '\x2', '\xA7', ',', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xAA', '\x5', '\x3', '\x2', '\x2', '\xA9', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '\xAA', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xB0', '\x5', '\r', '\a', '\x2', 
		'\xAE', '\xB0', '\x5', '\v', '\x6', '\x2', '\xAF', '\xAD', '\x3', '\x2', 
		'\x2', '\x2', '\xAF', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\a', 'k', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', 'h', '\x2', '\x2', '\xB3', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xB4', '\xB5', '\a', 'g', '\x2', '\x2', '\xB5', '\xB6', '\a', 
		'n', '\x2', '\x2', '\xB6', '\xB7', '\a', 'u', '\x2', '\x2', '\xB7', '\xB8', 
		'\a', 'g', '\x2', '\x2', '\xB8', '\x34', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBA', '\a', 'y', '\x2', '\x2', '\xBA', '\xBB', '\a', 'j', '\x2', '\x2', 
		'\xBB', '\xBC', '\a', 'k', '\x2', '\x2', '\xBC', '\xBD', '\a', 'n', '\x2', 
		'\x2', '\xBD', '\xBE', '\a', 'g', '\x2', '\x2', '\xBE', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\xC0', '\a', 'h', '\x2', '\x2', '\xC0', 
		'\xC1', '\a', 'q', '\x2', '\x2', '\xC1', '\xC2', '\a', 't', '\x2', '\x2', 
		'\xC2', '\x38', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\a', 'h', 
		'\x2', '\x2', '\xC4', '\xC5', '\a', 'w', '\x2', '\x2', '\xC5', '\xC6', 
		'\a', 'p', '\x2', '\x2', '\xC6', '\xC7', '\a', '\x65', '\x2', '\x2', '\xC7', 
		'\xC8', '\a', 'v', '\x2', '\x2', '\xC8', '\xC9', '\a', 'k', '\x2', '\x2', 
		'\xC9', '\xCA', '\a', 'q', '\x2', '\x2', '\xCA', '\xCB', '\a', 'p', '\x2', 
		'\x2', '\xCB', ':', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\a', 
		'-', '\x2', '\x2', '\xCD', '\xD6', '\a', '?', '\x2', '\x2', '\xCE', '\xCF', 
		'\a', '/', '\x2', '\x2', '\xCF', '\xD6', '\a', '?', '\x2', '\x2', '\xD0', 
		'\xD1', '\a', ',', '\x2', '\x2', '\xD1', '\xD6', '\a', '?', '\x2', '\x2', 
		'\xD2', '\xD3', '\a', '\x31', '\x2', '\x2', '\xD3', '\xD6', '\a', '?', 
		'\x2', '\x2', '\xD4', '\xD6', '\a', '?', '\x2', '\x2', '\xD5', '\xCC', 
		'\x3', '\x2', '\x2', '\x2', '\xD5', '\xCE', '\x3', '\x2', '\x2', '\x2', 
		'\xD5', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD2', '\x3', '\x2', 
		'\x2', '\x2', '\xD5', '\xD4', '\x3', '\x2', '\x2', '\x2', '\xD6', '<', 
		'\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\t', '\x6', '\x2', '\x2', 
		'\xD8', '>', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\t', '\a', '\x2', 
		'\x2', '\xDA', '@', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDC', '\a', 
		'`', '\x2', '\x2', '\xDC', '\x42', '\x3', '\x2', '\x2', '\x2', '\xDD', 
		'\xDE', '\x5', '\x1F', '\x10', '\x2', '\xDE', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\xDF', '\xE5', '\x5', '\x15', '\v', '\x2', '\xE0', '\xE5', '\x5', 
		'\x17', '\f', '\x2', '\xE1', '\xE5', '\x5', '\x19', '\r', '\x2', '\xE2', 
		'\xE5', '\x5', '\x1B', '\xE', '\x2', '\xE3', '\xE5', '\x5', '\x1D', '\xF', 
		'\x2', '\xE4', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE0', '\x3', 
		'\x2', '\x2', '\x2', '\xE4', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xE4', 
		'\xE2', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE3', '\x3', '\x2', '\x2', 
		'\x2', '\xE5', '\x46', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE7', '\a', 
		'(', '\x2', '\x2', '\xE7', '\xEB', '\a', '(', '\x2', '\x2', '\xE8', '\xE9', 
		'\a', '~', '\x2', '\x2', '\xE9', '\xEB', '\a', '~', '\x2', '\x2', '\xEA', 
		'\xE6', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xE8', '\x3', '\x2', '\x2', 
		'\x2', '\xEB', 'H', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', '\a', 
		'#', '\x2', '\x2', '\xED', 'J', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xF1', 
		'\x5', '\t', '\x5', '\x2', '\xEF', '\xF1', '\a', '\x61', '\x2', '\x2', 
		'\xF0', '\xEE', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xEF', '\x3', '\x2', 
		'\x2', '\x2', '\xF1', '\xF7', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF6', 
		'\x5', '\t', '\x5', '\x2', '\xF3', '\xF6', '\x5', '\x3', '\x2', '\x2', 
		'\xF4', '\xF6', '\a', '\x61', '\x2', '\x2', '\xF5', '\xF2', '\x3', '\x2', 
		'\x2', '\x2', '\xF5', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF4', 
		'\x3', '\x2', '\x2', '\x2', '\xF6', '\xF9', '\x3', '\x2', '\x2', '\x2', 
		'\xF7', '\xF5', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF8', '\x3', '\x2', 
		'\x2', '\x2', '\xF8', 'L', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xF7', 
		'\x3', '\x2', '\x2', '\x2', '\xFA', '\xFB', '\a', '*', '\x2', '\x2', '\xFB', 
		'N', '\x3', '\x2', '\x2', '\x2', '\xFC', '\xFD', '\a', '+', '\x2', '\x2', 
		'\xFD', 'P', '\x3', '\x2', '\x2', '\x2', '\xFE', '\xFF', '\a', '}', '\x2', 
		'\x2', '\xFF', 'R', '\x3', '\x2', '\x2', '\x2', '\x100', '\x101', '\a', 
		'\x7F', '\x2', '\x2', '\x101', 'T', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\x2', '\x8F', '\x97', '\xA2', '\xA6', '\xAB', '\xAF', '\xD5', '\xE4', 
		'\xEA', '\xF0', '\xF5', '\xF7', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace InterpreterLib
