//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace InterpreterLib {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GLangParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		STRING=1, CHAR_LITERAL=2, WHITESPACE=3, COMMA=4, TYPE_DELIMETER=5, BREAK=6, 
		CONTINUE=7, RETURN=8, TYPE_NAME=9, BOOLEAN=10, DOUBLE=11, BYTE=12, INTEGER=13, 
		DECL_VARIABLE=14, IF=15, ELSE=16, WHILE=17, FOR=18, FUNCTION=19, ASSIGNMENT_OPERATOR=20, 
		ADDITIVE_OP=21, MULTIPLICATIVE_OP=22, CARAT=23, LOW_PRIORITY_OP=24, COMPARE_OP=25, 
		LOGICAL_OP=26, BANG=27, IDENTIFIER=28, L_PARENTHESIS=29, R_PARENTHESIS=30, 
		L_BRACE=31, R_BRACE=32, UNKNOWN=33;
	public const int
		RULE_compilationUnit = 0, RULE_declerationOrAssign = 1, RULE_typeDefinition = 2, 
		RULE_globalStatement = 3, RULE_baseStatement = 4, RULE_statement = 5, 
		RULE_definedIdentifier = 6, RULE_seperatedDefinedIdentifier = 7, RULE_returnStatement = 8, 
		RULE_parameterDefinition = 9, RULE_functionDefinition = 10, RULE_block = 11, 
		RULE_expressionStatement = 12, RULE_forStatement = 13, RULE_ifStatement = 14, 
		RULE_pureIfStatement = 15, RULE_ifElseStatement = 16, RULE_whileStatement = 17, 
		RULE_variableDeclarationStatement = 18, RULE_assignmentOperand = 19, RULE_assignmentExpression = 20, 
		RULE_definedAssignment = 21, RULE_literal = 22, RULE_unaryExpression = 23, 
		RULE_binaryExpression = 24, RULE_expressionParameter = 25, RULE_functionCall = 26;
	public static readonly string[] ruleNames = {
		"compilationUnit", "declerationOrAssign", "typeDefinition", "globalStatement", 
		"baseStatement", "statement", "definedIdentifier", "seperatedDefinedIdentifier", 
		"returnStatement", "parameterDefinition", "functionDefinition", "block", 
		"expressionStatement", "forStatement", "ifStatement", "pureIfStatement", 
		"ifElseStatement", "whileStatement", "variableDeclarationStatement", "assignmentOperand", 
		"assignmentExpression", "definedAssignment", "literal", "unaryExpression", 
		"binaryExpression", "expressionParameter", "functionCall"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, "','", "':'", null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, "'^'", 
		null, null, null, "'!'", null, "'('", "')'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "STRING", "CHAR_LITERAL", "WHITESPACE", "COMMA", "TYPE_DELIMETER", 
		"BREAK", "CONTINUE", "RETURN", "TYPE_NAME", "BOOLEAN", "DOUBLE", "BYTE", 
		"INTEGER", "DECL_VARIABLE", "IF", "ELSE", "WHILE", "FOR", "FUNCTION", 
		"ASSIGNMENT_OPERATOR", "ADDITIVE_OP", "MULTIPLICATIVE_OP", "CARAT", "LOW_PRIORITY_OP", 
		"COMPARE_OP", "LOGICAL_OP", "BANG", "IDENTIFIER", "L_PARENTHESIS", "R_PARENTHESIS", 
		"L_BRACE", "R_BRACE", "UNKNOWN"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GLangParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public GLangParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public GLangParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class CompilationUnitContext : ParserRuleContext {
		public GlobalStatementContext[] globalStatement() {
			return GetRuleContexts<GlobalStatementContext>();
		}
		public GlobalStatementContext globalStatement(int i) {
			return GetRuleContext<GlobalStatementContext>(i);
		}
		public CompilationUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compilationUnit; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterCompilationUnit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitCompilationUnit(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompilationUnit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompilationUnitContext compilationUnit() {
		CompilationUnitContext _localctx = new CompilationUnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compilationUnit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 54; globalStatement();
				}
				}
				State = 57;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << CHAR_LITERAL) | (1L << BOOLEAN) | (1L << DOUBLE) | (1L << BYTE) | (1L << INTEGER) | (1L << DECL_VARIABLE) | (1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << FUNCTION) | (1L << ADDITIVE_OP) | (1L << BANG) | (1L << IDENTIFIER) | (1L << L_PARENTHESIS) | (1L << L_BRACE))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclerationOrAssignContext : ParserRuleContext {
		public VariableDeclarationStatementContext variableDeclarationStatement() {
			return GetRuleContext<VariableDeclarationStatementContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public DeclerationOrAssignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declerationOrAssign; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterDeclerationOrAssign(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitDeclerationOrAssign(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeclerationOrAssign(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclerationOrAssignContext declerationOrAssign() {
		DeclerationOrAssignContext _localctx = new DeclerationOrAssignContext(Context, State);
		EnterRule(_localctx, 2, RULE_declerationOrAssign);
		try {
			State = 61;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DECL_VARIABLE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 59; variableDeclarationStatement();
				}
				break;
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 60; assignmentExpression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeDefinitionContext : ParserRuleContext {
		public ITerminalNode TYPE_DELIMETER() { return GetToken(GLangParser.TYPE_DELIMETER, 0); }
		public ITerminalNode TYPE_NAME() { return GetToken(GLangParser.TYPE_NAME, 0); }
		public TypeDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterTypeDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitTypeDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeDefinitionContext typeDefinition() {
		TypeDefinitionContext _localctx = new TypeDefinitionContext(Context, State);
		EnterRule(_localctx, 4, RULE_typeDefinition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63; Match(TYPE_DELIMETER);
			State = 64; Match(TYPE_NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GlobalStatementContext : ParserRuleContext {
		public FunctionDefinitionContext functionDefinition() {
			return GetRuleContext<FunctionDefinitionContext>(0);
		}
		public BaseStatementContext baseStatement() {
			return GetRuleContext<BaseStatementContext>(0);
		}
		public GlobalStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_globalStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterGlobalStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitGlobalStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGlobalStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GlobalStatementContext globalStatement() {
		GlobalStatementContext _localctx = new GlobalStatementContext(Context, State);
		EnterRule(_localctx, 6, RULE_globalStatement);
		try {
			State = 68;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case FUNCTION:
				EnterOuterAlt(_localctx, 1);
				{
				State = 66; functionDefinition();
				}
				break;
			case STRING:
			case CHAR_LITERAL:
			case BOOLEAN:
			case DOUBLE:
			case BYTE:
			case INTEGER:
			case DECL_VARIABLE:
			case IF:
			case WHILE:
			case FOR:
			case ADDITIVE_OP:
			case BANG:
			case IDENTIFIER:
			case L_PARENTHESIS:
			case L_BRACE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 67; baseStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BaseStatementContext : ParserRuleContext {
		public ForStatementContext forStatement() {
			return GetRuleContext<ForStatementContext>(0);
		}
		public WhileStatementContext whileStatement() {
			return GetRuleContext<WhileStatementContext>(0);
		}
		public IfStatementContext ifStatement() {
			return GetRuleContext<IfStatementContext>(0);
		}
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public VariableDeclarationStatementContext variableDeclarationStatement() {
			return GetRuleContext<VariableDeclarationStatementContext>(0);
		}
		public ExpressionStatementContext expressionStatement() {
			return GetRuleContext<ExpressionStatementContext>(0);
		}
		public BaseStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_baseStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBaseStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBaseStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBaseStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BaseStatementContext baseStatement() {
		BaseStatementContext _localctx = new BaseStatementContext(Context, State);
		EnterRule(_localctx, 8, RULE_baseStatement);
		try {
			State = 76;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case FOR:
				EnterOuterAlt(_localctx, 1);
				{
				State = 70; forStatement();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 71; whileStatement();
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 3);
				{
				State = 72; ifStatement();
				}
				break;
			case L_BRACE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 73; block();
				}
				break;
			case DECL_VARIABLE:
				EnterOuterAlt(_localctx, 5);
				{
				State = 74; variableDeclarationStatement();
				}
				break;
			case STRING:
			case CHAR_LITERAL:
			case BOOLEAN:
			case DOUBLE:
			case BYTE:
			case INTEGER:
			case ADDITIVE_OP:
			case BANG:
			case IDENTIFIER:
			case L_PARENTHESIS:
				EnterOuterAlt(_localctx, 6);
				{
				State = 75; expressionStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public ReturnStatementContext returnStatement() {
			return GetRuleContext<ReturnStatementContext>(0);
		}
		public BaseStatementContext baseStatement() {
			return GetRuleContext<BaseStatementContext>(0);
		}
		public ITerminalNode BREAK() { return GetToken(GLangParser.BREAK, 0); }
		public ITerminalNode CONTINUE() { return GetToken(GLangParser.CONTINUE, 0); }
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 10, RULE_statement);
		try {
			State = 82;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case RETURN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 78; returnStatement();
				}
				break;
			case STRING:
			case CHAR_LITERAL:
			case BOOLEAN:
			case DOUBLE:
			case BYTE:
			case INTEGER:
			case DECL_VARIABLE:
			case IF:
			case WHILE:
			case FOR:
			case ADDITIVE_OP:
			case BANG:
			case IDENTIFIER:
			case L_PARENTHESIS:
			case L_BRACE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 79; baseStatement();
				}
				break;
			case BREAK:
				EnterOuterAlt(_localctx, 3);
				{
				State = 80; Match(BREAK);
				}
				break;
			case CONTINUE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 81; Match(CONTINUE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefinedIdentifierContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public TypeDefinitionContext typeDefinition() {
			return GetRuleContext<TypeDefinitionContext>(0);
		}
		public DefinedIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_definedIdentifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterDefinedIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitDefinedIdentifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefinedIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefinedIdentifierContext definedIdentifier() {
		DefinedIdentifierContext _localctx = new DefinedIdentifierContext(Context, State);
		EnterRule(_localctx, 12, RULE_definedIdentifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84; Match(IDENTIFIER);
			State = 85; typeDefinition();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SeperatedDefinedIdentifierContext : ParserRuleContext {
		public DefinedIdentifierContext definedIdentifier() {
			return GetRuleContext<DefinedIdentifierContext>(0);
		}
		public ITerminalNode COMMA() { return GetToken(GLangParser.COMMA, 0); }
		public SeperatedDefinedIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_seperatedDefinedIdentifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterSeperatedDefinedIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitSeperatedDefinedIdentifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSeperatedDefinedIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SeperatedDefinedIdentifierContext seperatedDefinedIdentifier() {
		SeperatedDefinedIdentifierContext _localctx = new SeperatedDefinedIdentifierContext(Context, State);
		EnterRule(_localctx, 14, RULE_seperatedDefinedIdentifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87; definedIdentifier();
			State = 88; Match(COMMA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnStatementContext : ParserRuleContext {
		public ITerminalNode RETURN() { return GetToken(GLangParser.RETURN, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ReturnStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterReturnStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitReturnStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturnStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReturnStatementContext returnStatement() {
		ReturnStatementContext _localctx = new ReturnStatementContext(Context, State);
		EnterRule(_localctx, 16, RULE_returnStatement);
		try {
			State = 93;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 90; Match(RETURN);
				State = 91; binaryExpression(0);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 92; Match(RETURN);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterDefinitionContext : ParserRuleContext {
		public DefinedIdentifierContext definedIdentifier() {
			return GetRuleContext<DefinedIdentifierContext>(0);
		}
		public ITerminalNode COMMA() { return GetToken(GLangParser.COMMA, 0); }
		public ParameterDefinitionContext parameterDefinition() {
			return GetRuleContext<ParameterDefinitionContext>(0);
		}
		public ParameterDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameterDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterParameterDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitParameterDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameterDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParameterDefinitionContext parameterDefinition() {
		ParameterDefinitionContext _localctx = new ParameterDefinitionContext(Context, State);
		EnterRule(_localctx, 18, RULE_parameterDefinition);
		try {
			State = 100;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 95; definedIdentifier();
				State = 96; Match(COMMA);
				State = 97; parameterDefinition();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 99; definedIdentifier();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDefinitionContext : ParserRuleContext {
		public ITerminalNode FUNCTION() { return GetToken(GLangParser.FUNCTION, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public ParameterDefinitionContext parameterDefinition() {
			return GetRuleContext<ParameterDefinitionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public TypeDefinitionContext typeDefinition() {
			return GetRuleContext<TypeDefinitionContext>(0);
		}
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public FunctionDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterFunctionDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitFunctionDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDefinitionContext functionDefinition() {
		FunctionDefinitionContext _localctx = new FunctionDefinitionContext(Context, State);
		EnterRule(_localctx, 20, RULE_functionDefinition);
		try {
			State = 117;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 102; Match(FUNCTION);
				State = 103; Match(IDENTIFIER);
				State = 104; Match(L_PARENTHESIS);
				State = 105; parameterDefinition();
				State = 106; Match(R_PARENTHESIS);
				State = 107; typeDefinition();
				State = 108; block();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 110; Match(FUNCTION);
				State = 111; Match(IDENTIFIER);
				State = 112; Match(L_PARENTHESIS);
				State = 113; Match(R_PARENTHESIS);
				State = 114; typeDefinition();
				State = 115; block();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public ITerminalNode L_BRACE() { return GetToken(GLangParser.L_BRACE, 0); }
		public ITerminalNode R_BRACE() { return GetToken(GLangParser.R_BRACE, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 22, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119; Match(L_BRACE);
			State = 123;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << CHAR_LITERAL) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << BOOLEAN) | (1L << DOUBLE) | (1L << BYTE) | (1L << INTEGER) | (1L << DECL_VARIABLE) | (1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << ADDITIVE_OP) | (1L << BANG) | (1L << IDENTIFIER) | (1L << L_PARENTHESIS) | (1L << L_BRACE))) != 0)) {
				{
				{
				State = 120; statement();
				}
				}
				State = 125;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 126; Match(R_BRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionStatementContext : ParserRuleContext {
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ExpressionStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterExpressionStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitExpressionStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionStatementContext expressionStatement() {
		ExpressionStatementContext _localctx = new ExpressionStatementContext(Context, State);
		EnterRule(_localctx, 24, RULE_expressionStatement);
		try {
			State = 130;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 128; assignmentExpression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 129; binaryExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForStatementContext : ParserRuleContext {
		public ITerminalNode FOR() { return GetToken(GLangParser.FOR, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public DeclerationOrAssignContext declerationOrAssign() {
			return GetRuleContext<DeclerationOrAssignContext>(0);
		}
		public ITerminalNode[] COMMA() { return GetTokens(GLangParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(GLangParser.COMMA, i);
		}
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public ForStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterForStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitForStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitForStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ForStatementContext forStatement() {
		ForStatementContext _localctx = new ForStatementContext(Context, State);
		EnterRule(_localctx, 26, RULE_forStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132; Match(FOR);
			State = 133; Match(L_PARENTHESIS);
			State = 134; declerationOrAssign();
			State = 135; Match(COMMA);
			State = 136; binaryExpression(0);
			State = 137; Match(COMMA);
			State = 138; assignmentExpression();
			State = 139; Match(R_PARENTHESIS);
			State = 140; statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementContext : ParserRuleContext {
		public IfElseStatementContext ifElseStatement() {
			return GetRuleContext<IfElseStatementContext>(0);
		}
		public PureIfStatementContext pureIfStatement() {
			return GetRuleContext<PureIfStatementContext>(0);
		}
		public IfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterIfStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitIfStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfStatementContext ifStatement() {
		IfStatementContext _localctx = new IfStatementContext(Context, State);
		EnterRule(_localctx, 28, RULE_ifStatement);
		try {
			State = 144;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 142; ifElseStatement();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 143; pureIfStatement();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PureIfStatementContext : ParserRuleContext {
		public StatementContext trueBranch;
		public ITerminalNode IF() { return GetToken(GLangParser.IF, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public PureIfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pureIfStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterPureIfStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitPureIfStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPureIfStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PureIfStatementContext pureIfStatement() {
		PureIfStatementContext _localctx = new PureIfStatementContext(Context, State);
		EnterRule(_localctx, 30, RULE_pureIfStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146; Match(IF);
			State = 147; Match(L_PARENTHESIS);
			State = 148; binaryExpression(0);
			State = 149; Match(R_PARENTHESIS);
			State = 150; _localctx.trueBranch = statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfElseStatementContext : ParserRuleContext {
		public StatementContext falseBranch;
		public PureIfStatementContext pureIfStatement() {
			return GetRuleContext<PureIfStatementContext>(0);
		}
		public ITerminalNode ELSE() { return GetToken(GLangParser.ELSE, 0); }
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public IfElseStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifElseStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterIfElseStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitIfElseStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfElseStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfElseStatementContext ifElseStatement() {
		IfElseStatementContext _localctx = new IfElseStatementContext(Context, State);
		EnterRule(_localctx, 32, RULE_ifElseStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152; pureIfStatement();
			State = 153; Match(ELSE);
			State = 154; _localctx.falseBranch = statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileStatementContext : ParserRuleContext {
		public StatementContext body;
		public ITerminalNode WHILE() { return GetToken(GLangParser.WHILE, 0); }
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public WhileStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterWhileStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitWhileStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhileStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhileStatementContext whileStatement() {
		WhileStatementContext _localctx = new WhileStatementContext(Context, State);
		EnterRule(_localctx, 34, RULE_whileStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156; Match(WHILE);
			State = 157; Match(L_PARENTHESIS);
			State = 158; binaryExpression(0);
			State = 159; Match(R_PARENTHESIS);
			State = 160; _localctx.body = statement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationStatementContext : ParserRuleContext {
		public ITerminalNode DECL_VARIABLE() { return GetToken(GLangParser.DECL_VARIABLE, 0); }
		public DefinedIdentifierContext definedIdentifier() {
			return GetRuleContext<DefinedIdentifierContext>(0);
		}
		public DefinedAssignmentContext definedAssignment() {
			return GetRuleContext<DefinedAssignmentContext>(0);
		}
		public VariableDeclarationStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclarationStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterVariableDeclarationStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitVariableDeclarationStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclarationStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationStatementContext variableDeclarationStatement() {
		VariableDeclarationStatementContext _localctx = new VariableDeclarationStatementContext(Context, State);
		EnterRule(_localctx, 36, RULE_variableDeclarationStatement);
		try {
			State = 166;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 162; Match(DECL_VARIABLE);
				State = 163; definedIdentifier();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 164; Match(DECL_VARIABLE);
				State = 165; definedAssignment();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentOperandContext : ParserRuleContext {
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public AssignmentOperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentOperand; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterAssignmentOperand(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitAssignmentOperand(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignmentOperand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentOperandContext assignmentOperand() {
		AssignmentOperandContext _localctx = new AssignmentOperandContext(Context, State);
		EnterRule(_localctx, 38, RULE_assignmentOperand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 168; binaryExpression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentExpressionContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ITerminalNode ASSIGNMENT_OPERATOR() { return GetToken(GLangParser.ASSIGNMENT_OPERATOR, 0); }
		public AssignmentOperandContext assignmentOperand() {
			return GetRuleContext<AssignmentOperandContext>(0);
		}
		public AssignmentExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterAssignmentExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitAssignmentExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignmentExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentExpressionContext assignmentExpression() {
		AssignmentExpressionContext _localctx = new AssignmentExpressionContext(Context, State);
		EnterRule(_localctx, 40, RULE_assignmentExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 170; Match(IDENTIFIER);
			State = 171; Match(ASSIGNMENT_OPERATOR);
			State = 172; assignmentOperand();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefinedAssignmentContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public TypeDefinitionContext typeDefinition() {
			return GetRuleContext<TypeDefinitionContext>(0);
		}
		public ITerminalNode ASSIGNMENT_OPERATOR() { return GetToken(GLangParser.ASSIGNMENT_OPERATOR, 0); }
		public AssignmentOperandContext assignmentOperand() {
			return GetRuleContext<AssignmentOperandContext>(0);
		}
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public DefinedAssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_definedAssignment; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterDefinedAssignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitDefinedAssignment(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefinedAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefinedAssignmentContext definedAssignment() {
		DefinedAssignmentContext _localctx = new DefinedAssignmentContext(Context, State);
		EnterRule(_localctx, 42, RULE_definedAssignment);
		try {
			State = 180;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 174; Match(IDENTIFIER);
				State = 175; typeDefinition();
				State = 176; Match(ASSIGNMENT_OPERATOR);
				State = 177; assignmentOperand();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 179; assignmentExpression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public ITerminalNode DOUBLE() { return GetToken(GLangParser.DOUBLE, 0); }
		public ITerminalNode INTEGER() { return GetToken(GLangParser.INTEGER, 0); }
		public ITerminalNode BOOLEAN() { return GetToken(GLangParser.BOOLEAN, 0); }
		public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public ITerminalNode STRING() { return GetToken(GLangParser.STRING, 0); }
		public ITerminalNode CHAR_LITERAL() { return GetToken(GLangParser.CHAR_LITERAL, 0); }
		public ITerminalNode BYTE() { return GetToken(GLangParser.BYTE, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 44, RULE_literal);
		try {
			State = 190;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 182; Match(DOUBLE);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 183; Match(INTEGER);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 184; Match(BOOLEAN);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 185; functionCall();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 186; Match(IDENTIFIER);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 187; Match(STRING);
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 188; Match(CHAR_LITERAL);
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 189; Match(BYTE);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryExpressionContext : ParserRuleContext {
		public IToken op;
		public LiteralContext atom;
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public UnaryExpressionContext unaryExpression() {
			return GetRuleContext<UnaryExpressionContext>(0);
		}
		public ITerminalNode ADDITIVE_OP() { return GetToken(GLangParser.ADDITIVE_OP, 0); }
		public ITerminalNode BANG() { return GetToken(GLangParser.BANG, 0); }
		public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public UnaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterUnaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitUnaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryExpressionContext unaryExpression() {
		UnaryExpressionContext _localctx = new UnaryExpressionContext(Context, State);
		EnterRule(_localctx, 46, RULE_unaryExpression);
		int _la;
		try {
			State = 199;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case L_PARENTHESIS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 192; Match(L_PARENTHESIS);
				State = 193; binaryExpression(0);
				State = 194; Match(R_PARENTHESIS);
				}
				break;
			case ADDITIVE_OP:
			case BANG:
				EnterOuterAlt(_localctx, 2);
				{
				State = 196;
				_localctx.op = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==ADDITIVE_OP || _la==BANG) ) {
					_localctx.op = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 197; unaryExpression();
				}
				break;
			case STRING:
			case CHAR_LITERAL:
			case BOOLEAN:
			case DOUBLE:
			case BYTE:
			case INTEGER:
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 3);
				{
				State = 198; _localctx.atom = literal();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinaryExpressionContext : ParserRuleContext {
		public BinaryExpressionContext left;
		public UnaryExpressionContext atom;
		public IToken op;
		public BinaryExpressionContext right;
		public UnaryExpressionContext unaryExpression() {
			return GetRuleContext<UnaryExpressionContext>(0);
		}
		public BinaryExpressionContext[] binaryExpression() {
			return GetRuleContexts<BinaryExpressionContext>();
		}
		public BinaryExpressionContext binaryExpression(int i) {
			return GetRuleContext<BinaryExpressionContext>(i);
		}
		public ITerminalNode CARAT() { return GetToken(GLangParser.CARAT, 0); }
		public ITerminalNode MULTIPLICATIVE_OP() { return GetToken(GLangParser.MULTIPLICATIVE_OP, 0); }
		public ITerminalNode ADDITIVE_OP() { return GetToken(GLangParser.ADDITIVE_OP, 0); }
		public ITerminalNode LOW_PRIORITY_OP() { return GetToken(GLangParser.LOW_PRIORITY_OP, 0); }
		public ITerminalNode COMPARE_OP() { return GetToken(GLangParser.COMPARE_OP, 0); }
		public ITerminalNode LOGICAL_OP() { return GetToken(GLangParser.LOGICAL_OP, 0); }
		public BinaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterBinaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitBinaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BinaryExpressionContext binaryExpression() {
		return binaryExpression(0);
	}

	private BinaryExpressionContext binaryExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BinaryExpressionContext _localctx = new BinaryExpressionContext(Context, _parentState);
		BinaryExpressionContext _prevctx = _localctx;
		int _startState = 48;
		EnterRecursionRule(_localctx, 48, RULE_binaryExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 202; _localctx.atom = unaryExpression();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 224;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 222;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
					case 1:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 204;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 205; _localctx.op = Match(CARAT);
						State = 206; _localctx.right = binaryExpression(8);
						}
						break;
					case 2:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 207;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 208; _localctx.op = Match(MULTIPLICATIVE_OP);
						State = 209; _localctx.right = binaryExpression(7);
						}
						break;
					case 3:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 210;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 211; _localctx.op = Match(ADDITIVE_OP);
						State = 212; _localctx.right = binaryExpression(6);
						}
						break;
					case 4:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 213;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 214; _localctx.op = Match(LOW_PRIORITY_OP);
						State = 215; _localctx.right = binaryExpression(5);
						}
						break;
					case 5:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 216;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 217; _localctx.op = Match(COMPARE_OP);
						State = 218; _localctx.right = binaryExpression(4);
						}
						break;
					case 6:
						{
						_localctx = new BinaryExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpression);
						State = 219;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 220; _localctx.op = Match(LOGICAL_OP);
						State = 221; _localctx.right = binaryExpression(3);
						}
						break;
					}
					} 
				}
				State = 226;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ExpressionParameterContext : ParserRuleContext {
		public BinaryExpressionContext binaryExpression() {
			return GetRuleContext<BinaryExpressionContext>(0);
		}
		public ITerminalNode COMMA() { return GetToken(GLangParser.COMMA, 0); }
		public ExpressionParameterContext expressionParameter() {
			return GetRuleContext<ExpressionParameterContext>(0);
		}
		public ExpressionParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionParameter; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterExpressionParameter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitExpressionParameter(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionParameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionParameterContext expressionParameter() {
		ExpressionParameterContext _localctx = new ExpressionParameterContext(Context, State);
		EnterRule(_localctx, 50, RULE_expressionParameter);
		try {
			State = 232;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 227; binaryExpression(0);
				State = 228; Match(COMMA);
				State = 229; expressionParameter();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 231; binaryExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionCallContext : ParserRuleContext {
		public IToken funcName;
		public ITerminalNode L_PARENTHESIS() { return GetToken(GLangParser.L_PARENTHESIS, 0); }
		public ExpressionParameterContext expressionParameter() {
			return GetRuleContext<ExpressionParameterContext>(0);
		}
		public ITerminalNode R_PARENTHESIS() { return GetToken(GLangParser.R_PARENTHESIS, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(GLangParser.IDENTIFIER, 0); }
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.EnterFunctionCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGLangListener typedListener = listener as IGLangListener;
			if (typedListener != null) typedListener.ExitFunctionCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGLangVisitor<TResult> typedVisitor = visitor as IGLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 52, RULE_functionCall);
		try {
			State = 242;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 234; _localctx.funcName = Match(IDENTIFIER);
				State = 235; Match(L_PARENTHESIS);
				State = 236; expressionParameter();
				State = 237; Match(R_PARENTHESIS);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 239; _localctx.funcName = Match(IDENTIFIER);
				State = 240; Match(L_PARENTHESIS);
				State = 241; Match(R_PARENTHESIS);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 24: return binaryExpression_sempred((BinaryExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool binaryExpression_sempred(BinaryExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 7);
		case 1: return Precpred(Context, 6);
		case 2: return Precpred(Context, 5);
		case 3: return Precpred(Context, 4);
		case 4: return Precpred(Context, 3);
		case 5: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '#', '\xF7', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x3', '\x2', '\x6', 
		'\x2', ':', '\n', '\x2', '\r', '\x2', '\xE', '\x2', ';', '\x3', '\x3', 
		'\x3', '\x3', '\x5', '\x3', '@', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 'G', '\n', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x5', '\x6', 'O', '\n', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x5', '\a', 'U', '\n', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x5', '\n', '`', '\n', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', 'g', '\n', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', 'x', 
		'\n', '\f', '\x3', '\r', '\x3', '\r', '\a', '\r', '|', '\n', '\r', '\f', 
		'\r', '\xE', '\r', '\x7F', '\v', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x5', '\xE', '\x85', '\n', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x5', '\x10', '\x93', '\n', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', '\xA9', 
		'\n', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\xB7', '\n', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x5', '\x18', '\xC1', 
		'\n', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x5', '\x19', '\xCA', '\n', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\a', '\x1A', '\xE1', '\n', '\x1A', '\f', '\x1A', 
		'\xE', '\x1A', '\xE4', '\v', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x5', '\x1B', '\xEB', '\n', '\x1B', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x5', '\x1C', '\xF5', '\n', 
		'\x1C', '\x3', '\x1C', '\x2', '\x3', '\x32', '\x1D', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', 
		'\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', '\x30', '\x32', 
		'\x34', '\x36', '\x2', '\x3', '\x4', '\x2', '\x17', '\x17', '\x1D', '\x1D', 
		'\x2', '\xFF', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x4', '?', 
		'\x3', '\x2', '\x2', '\x2', '\x6', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\b', '\x46', '\x3', '\x2', '\x2', '\x2', '\n', 'N', '\x3', '\x2', '\x2', 
		'\x2', '\f', 'T', '\x3', '\x2', '\x2', '\x2', '\xE', 'V', '\x3', '\x2', 
		'\x2', '\x2', '\x10', 'Y', '\x3', '\x2', '\x2', '\x2', '\x12', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x14', '\x66', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'w', '\x3', '\x2', '\x2', '\x2', '\x18', 'y', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', '\x84', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x86', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\x92', '\x3', '\x2', '\x2', '\x2', ' ', '\x94', 
		'\x3', '\x2', '\x2', '\x2', '\"', '\x9A', '\x3', '\x2', '\x2', '\x2', 
		'$', '\x9E', '\x3', '\x2', '\x2', '\x2', '&', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '(', '\xAA', '\x3', '\x2', '\x2', '\x2', '*', '\xAC', '\x3', '\x2', 
		'\x2', '\x2', ',', '\xB6', '\x3', '\x2', '\x2', '\x2', '.', '\xC0', '\x3', 
		'\x2', '\x2', '\x2', '\x30', '\xC9', '\x3', '\x2', '\x2', '\x2', '\x32', 
		'\xCB', '\x3', '\x2', '\x2', '\x2', '\x34', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '\x36', '\xF4', '\x3', '\x2', '\x2', '\x2', '\x38', ':', '\x5', 
		'\b', '\x5', '\x2', '\x39', '\x38', '\x3', '\x2', '\x2', '\x2', ':', ';', 
		'\x3', '\x2', '\x2', '\x2', ';', '\x39', '\x3', '\x2', '\x2', '\x2', ';', 
		'<', '\x3', '\x2', '\x2', '\x2', '<', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'=', '@', '\x5', '&', '\x14', '\x2', '>', '@', '\x5', '*', '\x16', '\x2', 
		'?', '=', '\x3', '\x2', '\x2', '\x2', '?', '>', '\x3', '\x2', '\x2', '\x2', 
		'@', '\x5', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\a', '\x2', 
		'\x2', '\x42', '\x43', '\a', '\v', '\x2', '\x2', '\x43', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x44', 'G', '\x5', '\x16', '\f', '\x2', '\x45', 
		'G', '\x5', '\n', '\x6', '\x2', '\x46', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'\x46', '\x45', '\x3', '\x2', '\x2', '\x2', 'G', '\t', '\x3', '\x2', '\x2', 
		'\x2', 'H', 'O', '\x5', '\x1C', '\xF', '\x2', 'I', 'O', '\x5', '$', '\x13', 
		'\x2', 'J', 'O', '\x5', '\x1E', '\x10', '\x2', 'K', 'O', '\x5', '\x18', 
		'\r', '\x2', 'L', 'O', '\x5', '&', '\x14', '\x2', 'M', 'O', '\x5', '\x1A', 
		'\xE', '\x2', 'N', 'H', '\x3', '\x2', '\x2', '\x2', 'N', 'I', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'J', '\x3', '\x2', '\x2', '\x2', 'N', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'L', '\x3', '\x2', '\x2', '\x2', 'N', 'M', '\x3', '\x2', 
		'\x2', '\x2', 'O', '\v', '\x3', '\x2', '\x2', '\x2', 'P', 'U', '\x5', 
		'\x12', '\n', '\x2', 'Q', 'U', '\x5', '\n', '\x6', '\x2', 'R', 'U', '\a', 
		'\b', '\x2', '\x2', 'S', 'U', '\a', '\t', '\x2', '\x2', 'T', 'P', '\x3', 
		'\x2', '\x2', '\x2', 'T', 'Q', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', 
		'\x2', '\x2', '\x2', 'T', 'S', '\x3', '\x2', '\x2', '\x2', 'U', '\r', 
		'\x3', '\x2', '\x2', '\x2', 'V', 'W', '\a', '\x1E', '\x2', '\x2', 'W', 
		'X', '\x5', '\x6', '\x4', '\x2', 'X', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'Y', 'Z', '\x5', '\xE', '\b', '\x2', 'Z', '[', '\a', '\x6', '\x2', '\x2', 
		'[', '\x11', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\a', '\n', '\x2', 
		'\x2', ']', '`', '\x5', '\x32', '\x1A', '\x2', '^', '`', '\a', '\n', '\x2', 
		'\x2', '_', '\\', '\x3', '\x2', '\x2', '\x2', '_', '^', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x13', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', 
		'\x5', '\xE', '\b', '\x2', '\x62', '\x63', '\a', '\x6', '\x2', '\x2', 
		'\x63', '\x64', '\x5', '\x14', '\v', '\x2', '\x64', 'g', '\x3', '\x2', 
		'\x2', '\x2', '\x65', 'g', '\x5', '\xE', '\b', '\x2', '\x66', '\x61', 
		'\x3', '\x2', '\x2', '\x2', '\x66', '\x65', '\x3', '\x2', '\x2', '\x2', 
		'g', '\x15', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\a', '\x15', '\x2', 
		'\x2', 'i', 'j', '\a', '\x1E', '\x2', '\x2', 'j', 'k', '\a', '\x1F', '\x2', 
		'\x2', 'k', 'l', '\x5', '\x14', '\v', '\x2', 'l', 'm', '\a', ' ', '\x2', 
		'\x2', 'm', 'n', '\x5', '\x6', '\x4', '\x2', 'n', 'o', '\x5', '\x18', 
		'\r', '\x2', 'o', 'x', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '\x15', 
		'\x2', '\x2', 'q', 'r', '\a', '\x1E', '\x2', '\x2', 'r', 's', '\a', '\x1F', 
		'\x2', '\x2', 's', 't', '\a', ' ', '\x2', '\x2', 't', 'u', '\x5', '\x6', 
		'\x4', '\x2', 'u', 'v', '\x5', '\x18', '\r', '\x2', 'v', 'x', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'h', '\x3', '\x2', '\x2', '\x2', 'w', 'p', '\x3', '\x2', 
		'\x2', '\x2', 'x', '\x17', '\x3', '\x2', '\x2', '\x2', 'y', '}', '\a', 
		'!', '\x2', '\x2', 'z', '|', '\x5', '\f', '\a', '\x2', '{', 'z', '\x3', 
		'\x2', '\x2', '\x2', '|', '\x7F', '\x3', '\x2', '\x2', '\x2', '}', '{', 
		'\x3', '\x2', '\x2', '\x2', '}', '~', '\x3', '\x2', '\x2', '\x2', '~', 
		'\x80', '\x3', '\x2', '\x2', '\x2', '\x7F', '}', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x81', '\a', '\"', '\x2', '\x2', '\x81', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x85', '\x5', '*', '\x16', '\x2', '\x83', 
		'\x85', '\x5', '\x32', '\x1A', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x83', '\x3', '\x2', '\x2', '\x2', '\x85', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x87', '\a', '\x14', '\x2', '\x2', '\x87', 
		'\x88', '\a', '\x1F', '\x2', '\x2', '\x88', '\x89', '\x5', '\x4', '\x3', 
		'\x2', '\x89', '\x8A', '\a', '\x6', '\x2', '\x2', '\x8A', '\x8B', '\x5', 
		'\x32', '\x1A', '\x2', '\x8B', '\x8C', '\a', '\x6', '\x2', '\x2', '\x8C', 
		'\x8D', '\x5', '*', '\x16', '\x2', '\x8D', '\x8E', '\a', ' ', '\x2', '\x2', 
		'\x8E', '\x8F', '\x5', '\f', '\a', '\x2', '\x8F', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x93', '\x5', '\"', '\x12', '\x2', '\x91', '\x93', 
		'\x5', ' ', '\x11', '\x2', '\x92', '\x90', '\x3', '\x2', '\x2', '\x2', 
		'\x92', '\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x94', '\x95', '\a', '\x11', '\x2', '\x2', '\x95', '\x96', 
		'\a', '\x1F', '\x2', '\x2', '\x96', '\x97', '\x5', '\x32', '\x1A', '\x2', 
		'\x97', '\x98', '\a', ' ', '\x2', '\x2', '\x98', '\x99', '\x5', '\f', 
		'\a', '\x2', '\x99', '!', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', 
		'\x5', ' ', '\x11', '\x2', '\x9B', '\x9C', '\a', '\x12', '\x2', '\x2', 
		'\x9C', '\x9D', '\x5', '\f', '\a', '\x2', '\x9D', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9F', '\a', '\x13', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		'\x1F', '\x2', '\x2', '\xA0', '\xA1', '\x5', '\x32', '\x1A', '\x2', '\xA1', 
		'\xA2', '\a', ' ', '\x2', '\x2', '\xA2', '\xA3', '\x5', '\f', '\a', '\x2', 
		'\xA3', '%', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', '\x10', 
		'\x2', '\x2', '\xA5', '\xA9', '\x5', '\xE', '\b', '\x2', '\xA6', '\xA7', 
		'\a', '\x10', '\x2', '\x2', '\xA7', '\xA9', '\x5', ',', '\x17', '\x2', 
		'\xA8', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '\xA9', '\'', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', 
		'\x5', '\x32', '\x1A', '\x2', '\xAB', ')', '\x3', '\x2', '\x2', '\x2', 
		'\xAC', '\xAD', '\a', '\x1E', '\x2', '\x2', '\xAD', '\xAE', '\a', '\x16', 
		'\x2', '\x2', '\xAE', '\xAF', '\x5', '(', '\x15', '\x2', '\xAF', '+', 
		'\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\a', '\x1E', '\x2', '\x2', 
		'\xB1', '\xB2', '\x5', '\x6', '\x4', '\x2', '\xB2', '\xB3', '\a', '\x16', 
		'\x2', '\x2', '\xB3', '\xB4', '\x5', '(', '\x15', '\x2', '\xB4', '\xB7', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB7', '\x5', '*', '\x16', '\x2', 
		'\xB6', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB5', '\x3', '\x2', 
		'\x2', '\x2', '\xB7', '-', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xC1', 
		'\a', '\r', '\x2', '\x2', '\xB9', '\xC1', '\a', '\xF', '\x2', '\x2', '\xBA', 
		'\xC1', '\a', '\f', '\x2', '\x2', '\xBB', '\xC1', '\x5', '\x36', '\x1C', 
		'\x2', '\xBC', '\xC1', '\a', '\x1E', '\x2', '\x2', '\xBD', '\xC1', '\a', 
		'\x3', '\x2', '\x2', '\xBE', '\xC1', '\a', '\x4', '\x2', '\x2', '\xBF', 
		'\xC1', '\a', '\xE', '\x2', '\x2', '\xC0', '\xB8', '\x3', '\x2', '\x2', 
		'\x2', '\xC0', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xBA', '\x3', 
		'\x2', '\x2', '\x2', '\xC0', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\xC0', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xC1', '/', '\x3', '\x2', '\x2', '\x2', '\xC2', 
		'\xC3', '\a', '\x1F', '\x2', '\x2', '\xC3', '\xC4', '\x5', '\x32', '\x1A', 
		'\x2', '\xC4', '\xC5', '\a', ' ', '\x2', '\x2', '\xC5', '\xCA', '\x3', 
		'\x2', '\x2', '\x2', '\xC6', '\xC7', '\t', '\x2', '\x2', '\x2', '\xC7', 
		'\xCA', '\x5', '\x30', '\x19', '\x2', '\xC8', '\xCA', '\x5', '.', '\x18', 
		'\x2', '\xC9', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC6', '\x3', 
		'\x2', '\x2', '\x2', '\xC9', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xCC', '\b', '\x1A', '\x1', 
		'\x2', '\xCC', '\xCD', '\x5', '\x30', '\x19', '\x2', '\xCD', '\xE2', '\x3', 
		'\x2', '\x2', '\x2', '\xCE', '\xCF', '\f', '\t', '\x2', '\x2', '\xCF', 
		'\xD0', '\a', '\x19', '\x2', '\x2', '\xD0', '\xE1', '\x5', '\x32', '\x1A', 
		'\n', '\xD1', '\xD2', '\f', '\b', '\x2', '\x2', '\xD2', '\xD3', '\a', 
		'\x18', '\x2', '\x2', '\xD3', '\xE1', '\x5', '\x32', '\x1A', '\t', '\xD4', 
		'\xD5', '\f', '\a', '\x2', '\x2', '\xD5', '\xD6', '\a', '\x17', '\x2', 
		'\x2', '\xD6', '\xE1', '\x5', '\x32', '\x1A', '\b', '\xD7', '\xD8', '\f', 
		'\x6', '\x2', '\x2', '\xD8', '\xD9', '\a', '\x1A', '\x2', '\x2', '\xD9', 
		'\xE1', '\x5', '\x32', '\x1A', '\a', '\xDA', '\xDB', '\f', '\x5', '\x2', 
		'\x2', '\xDB', '\xDC', '\a', '\x1B', '\x2', '\x2', '\xDC', '\xE1', '\x5', 
		'\x32', '\x1A', '\x6', '\xDD', '\xDE', '\f', '\x4', '\x2', '\x2', '\xDE', 
		'\xDF', '\a', '\x1C', '\x2', '\x2', '\xDF', '\xE1', '\x5', '\x32', '\x1A', 
		'\x5', '\xE0', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xD1', '\x3', 
		'\x2', '\x2', '\x2', '\xE0', '\xD4', '\x3', '\x2', '\x2', '\x2', '\xE0', 
		'\xD7', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xDA', '\x3', '\x2', '\x2', 
		'\x2', '\xE0', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xE1', '\xE4', '\x3', 
		'\x2', '\x2', '\x2', '\xE2', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE2', 
		'\xE3', '\x3', '\x2', '\x2', '\x2', '\xE3', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\xE4', '\xE2', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE6', '\x5', 
		'\x32', '\x1A', '\x2', '\xE6', '\xE7', '\a', '\x6', '\x2', '\x2', '\xE7', 
		'\xE8', '\x5', '\x34', '\x1B', '\x2', '\xE8', '\xEB', '\x3', '\x2', '\x2', 
		'\x2', '\xE9', '\xEB', '\x5', '\x32', '\x1A', '\x2', '\xEA', '\xE5', '\x3', 
		'\x2', '\x2', '\x2', '\xEA', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xEB', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', '\a', '\x1E', '\x2', 
		'\x2', '\xED', '\xEE', '\a', '\x1F', '\x2', '\x2', '\xEE', '\xEF', '\x5', 
		'\x34', '\x1B', '\x2', '\xEF', '\xF0', '\a', ' ', '\x2', '\x2', '\xF0', 
		'\xF5', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xF2', '\a', '\x1E', '\x2', 
		'\x2', '\xF2', '\xF3', '\a', '\x1F', '\x2', '\x2', '\xF3', '\xF5', '\a', 
		' ', '\x2', '\x2', '\xF4', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xF4', 
		'\xF1', '\x3', '\x2', '\x2', '\x2', '\xF5', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '\x15', ';', '?', '\x46', 'N', 'T', '_', '\x66', 'w', '}', '\x84', 
		'\x92', '\xA8', '\xB6', '\xC0', '\xC9', '\xE0', '\xE2', '\xEA', '\xF4',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace InterpreterLib
